README.md

@munificent  @kwalrath 
I've incorporated Kathy's feedback on the gist page. Thanks!

Merging the dartlang dartfmt page with this page.

---

lib/src/source_visitor.dart

We'll want to add a type for the parameter and remove the explicit type on the list literal after updating the dependency constraints.

Implement visitor method to be added in the analyzer package

---

CHANGELOG.md
bin/format.dart
lib/src/source_visitor.dart
pubspec.yaml
test/splitting/generic_method_parameters.unit
test/splitting/type_parameters.unit
test/utils.dart

Previous support only covered arguments. :(

Support generic method parameters.

---

lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml

Update SourceVisitor to extend ThrowingAstVisitor

---

CHANGELOG.md
bin/format.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/formatter_test.dart
test/splitting/members.unit
test/splitting/parameters.unit
test/whitespace/classes.unit
test/whitespace/metadata.unit
test/whitespace/methods.unit

Support "covariant" modifier.

---

CHANGELOG.md
example/format.dart
lib/src/argument_list_visitor.dart
test/regression/0500/0566.unit

Handle parenthesized and immediately invoked functions better.

---

CHANGELOG.md
lib/src/source_visitor.dart
test/regression/0500/0541.unit
test/whitespace/native.unit

Don't add a spurious space after "native".

---

CHANGELOG.md
bin/format.dart
pubspec.yaml

Bump version to 1.0.0.

---

CHANGELOG.md
lib/src/source_visitor.dart
pubspec.yaml
test/regression/0100/0170.unit
test/whitespace/expressions.stmt

Ensure space between `-` and `--`.

---

CHANGELOG.md
bin/format.dart
lib/src/argument_list_visitor.dart
pubspec.yaml
test/formatter_test.dart

I'd like to get this out and into the SDK since it adds support for
asserts in initializers.

Get ready to publish 1.0.7.

---

README.md

Dart syntax highlighting is supported in Github markdown.

readme.md updated (Dart syntax)

---

pubspec.lock
pubspec.yaml

Support latest analyzer and async packages

---

CHANGELOG.md
lib/src/source_visitor.dart
pubspec.yaml
test/regression/0600/0648.stmt
test/whitespace/metadata.unit

Preserve metadata on for-in loop variables.

---

lib/src/source_visitor.dart
test/regression/0600/0658.unit

No new line before initializer list on constructor with trailling comma

---

CHANGELOG.md
bin/format.dart
lib/src/source_visitor.dart
pubspec.yaml

Thanks for mentioning this! It was the only issue I found. All tests pass on the VM with `--preview-dart-2` now.

Fix an issue when running in Dart 2.

---

CHANGELOG.md
bin/format.dart
lib/src/io.dart
pubspec.lock
pubspec.yaml

Also use new constants names in dart:io from 2-dev.54
Also prepare to release 1.0.13

Support the latest pkg:analyzer

---

CHANGELOG.md
bin/format.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/whitespace/metadata.unit

Add support for metadata on enum cases.

---

CHANGELOG.md
analysis_options.yaml
pubspec.lock
pubspec.yaml

chore: set max SDK version to <3.0.0

---

lib/src/debug.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/formatter_test.dart

Fix a few static warnings and lints.

---

CHANGELOG.md
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/splitting/mixins.unit
test/whitespace/metadata.unit
test/whitespace/mixins.unit

Add support for new Dart 2.1 mixin syntax.

---

CHANGELOG.md
bin/format.dart
test/command_line_test.dart

Let users control name shown in errors when reading from stdin.

---

bin/format.dart
pubspec.yaml
test/command_line_test.dart

(Also fix a tiny missing await.)

Bump version to publish 1.2.0.

---

CHANGELOG.md
bin/format.dart
lib/src/argument_list_visitor.dart
lib/src/call_chain_visitor.dart
lib/src/dart_formatter.dart
lib/src/error_listener.dart
lib/src/exceptions.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml

Also fix imports to deprecated analyzer library.

Upgrade to analyzer 0.34.0 and get ready to publish 1.2.1.

---

CHANGELOG.md
bin/format.dart
lib/src/dart_formatter.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/comments/sets.stmt
test/splitting/sets.stmt
test/whitespace/expressions.stmt

Add support for set literals.

---

lib/src/dart_formatter.dart
pubspec.yaml

This helps prepare for the next major version of the analyzer package.

Use featureSet parameter to configure the parser.

---

CHANGELOG.md
lib/src/call_chain_visitor.dart
lib/src/line_splitting/solve_state.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/splitting/list_collection_if.stmt

Avoid needless indentation on chained if-else elements.

---

CHANGELOG.md
codereview.settings
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml

Also fixed new lint about `whereType`

Support latest pkg:analyzer, prepare to release 1.2.9

---

CHANGELOG.md
bin/format.dart
pubspec.lock
pubspec.yaml

Update to analyzer 0.38.0

---

pubspec.lock
pubspec.yaml
test/splitting/invocations.stmt
test/whitespace/expressions.stmt

Now that it correctly parses method chains with null assertion
operators, add some more tests around that.

Update to analyzer 0.38.3.

---

CHANGELOG.md
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/whitespace/classes.unit
test/whitespace/compilation_unit.unit
test/whitespace/metadata.unit
test/whitespace/statements.stmt

One more piece of NNBD support.

Format the "late" modifier.

---

CHANGELOG.md
lib/src/source_visitor.dart
test/fixes/function_typedefs.unit
test/fixes/named_default_separator.unit
test/splitting/parameters.unit
test/whitespace/functions.unit
test/whitespace/metadata.unit

Format the new "required" modifier.

---

CHANGELOG.md
pubspec.lock
pubspec.yaml
tool/grind.dart
tool/node_format_service.dart

Reverts dart-lang/dart_style#787
dart-style needs to be updated for js_facade_gen

Revert "Remove npm bits"

---

CHANGELOG.md
bin/format.dart
pubspec.lock
pubspec.yaml

Closes #866
- Increase the range for the dependency.
- Pub upgrade.
- Bump version and prepare to publish.

Support analyzer 0.39.0

---

CHANGELOG.md
lib/src/source_visitor.dart
pubspec.yaml
test/fixes/function_typedefs.unit

Correctly handle "var" in --fix-function-typedefs.

---

pubspec.lock

Update dependencies again

---

CHANGELOG.md
lib/src/source_visitor.dart
test/regression/0800/0869.stmt
test/splitting/list_collection_for.stmt
test/splitting/list_collection_if.stmt
test/splitting/map_collection_for.stmt
test/splitting/map_collection_if.stmt
test/splitting/set_collection_for.stmt
test/splitting/set_collection_if.stmt

For split control flow elements that contain other ones.

---

CHANGELOG.md
lib/src/source_visitor.dart
test/regression/0800/0888.unit

Don't add unneeded splits on if elements near comments.

---

bin/format.dart
lib/src/cli/format_command.dart
lib/src/cli/formatter_options.dart
lib/src/cli/options.dart
lib/src/cli/output.dart
lib/src/cli/show.dart
lib/src/cli/summary.dart
lib/src/io.dart
test/command_line_test.dart
test/command_test.dart
test/io_test.dart
test/utils.dart
tool/command_shell.dart
tool/grind.dart

I know this is a huge amount of code changes, but it was the best I could do not break the old CLI while also not compromising the new UI. I've broken it into a series of commits to hopefully make it easier to review, and added copious tests to make sure everything works as expected.
Fix #889.

Add a hidden Command library for integrating into dartdev

---

CHANGELOG.md

I ended up removing "--verbose".

Remove unnecessary changelog entries.

---

CHANGELOG.md
lib/src/cli/formatter_options.dart
pubspec.yaml

Bump to 1.3.5.

---

lib/src/cli/formatter_options.dart
pubspec.yaml

Oops, meant to do this in the last commit.
Thanks for all the reviews!

Bump to 1.3.6.

---

CHANGELOG.md
lib/src/cli/formatter_options.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml
test/regression/0900/0960.unit
test/whitespace/functions.unit

Preserve "?" in function-typed initializing formals.

---

lib/src/cli/format_command.dart
lib/src/cli/formatter_options.dart
pubspec.lock
pubspec.yaml
tool/command_shell.dart

Make FormatCommand implement Command<int>.

---

test/io_test.dart

As of Dart 2.1, Future/Stream have been exported from dart:core.

Remove unused dart:async imports.

---

lib/src/cli/options.dart
test/command_line_test.dart

See: https://github.com/dart-lang/sdk/issues/44023

Always show "--set-exit-if-changed" in help.

---

CHANGELOG.md
lib/src/cli/formatter_options.dart
pubspec.lock
pubspec.yaml

Closes https://github.com/dart-lang/dart_style/issues/976

allow analyzer version 0.41.0

---

lib/src/cli/formatter_options.dart
pubspec.yaml

I'm going to publish this so I can roll the performance fix in since
it's hitting some internal generated code.

Bump to 1.3.11.

---

CHANGELOG.md
lib/src/cli/format_command.dart

Related to https://github.com/dart-lang/sdk/issues/44582

Return exitCode from FormatCommand.run()

---

lib/src/cli/formatter_options.dart

Update internal version number too.

---

lib/src/cli/formatter_options.dart
pubspec.yaml

Just a tiny PR to bump the version so I can publish 2.0.0 (after I roll it into the SDK and Google).

Get ready to publish 2.0.0.

---

CHANGELOG.md
lib/src/source_visitor.dart
test/regression/1000/1010.unit

Correct constructor initializer indentation after "required".

---

CHANGELOG.md
lib/src/argument_list_visitor.dart
lib/src/nesting_level.dart
lib/src/source_visitor.dart
test/regression/1000/1029.unit
test/splitting/statements.stmt

Split empty catch blocks with finally clauses.

---

CHANGELOG.md
lib/src/source_visitor.dart
test/regression/1000/1029.unit
test/splitting/statements.stmt

Addresses: https://github.com/dart-lang/dart_style/pull/1041#issuecomment-873153888

Split empty catch

---

.github/workflows/test-package.yml
CHANGELOG.md
lib/src/cli/formatter_options.dart
lib/src/source_visitor.dart
pubspec.lock
pubspec.yaml

Thanks for all the code reviews!

Bump version to publish 2.0.2.

---

test/regression/0400/0479.stmt

Add a regression test for #479, which is working as intended now.

---

CHANGELOG.md
pubspec.lock
pubspec.yaml

~Overriding to that version for testing purposes, will remove the override before submitting.~ reverted now, tests were good
Towards https://github.com/dart-lang/dart_style/issues/1078

allow analyzer version 3.0.0

---

benchmark/benchmark.dart
lib/src/cli/format_command.dart
lib/src/cli/formatter_options.dart
lib/src/cli/output.dart
lib/src/cli/show.dart
lib/src/debug.dart
lib/src/exceptions.dart
lib/src/fast_hash.dart
lib/src/line_splitting/line_splitter.dart
lib/src/line_splitting/rule_set.dart
lib/src/line_splitting/solve_state.dart
lib/src/nesting_builder.dart
lib/src/nesting_level.dart
lib/src/rule/combinator.dart
lib/src/rule/type_argument.dart
lib/src/source_code.dart
pubspec.lock
pubspec.yaml
test/command_line_test.dart
test/io_test.dart
test/source_code_test.dart

Also some other minor clean-up while I was at it:
- Remove unneeded library tags.
- Fix some raw typed collections.
- Use list element where it makes sense.
- Remove unneeded .whereType<Rule>() calls. (They were to filter out
null, but the rule field is non-nullable now.)

Refactor to use enhanced enums for Output and Show.

---

lib/src/source_visitor.dart

From feedback at https://github.com/dart-lang/dart_style/pull/1144#discussion_r987438824

Simplify visits with optional names

---

CHANGELOG.md
lib/src/dart_formatter.dart
lib/src/source_visitor.dart
test/whitespace/classes.unit
test/whitespace/mixins.unit

This is an easy one. I tested this on @kallentu's language tests and it looks like it's covering everything.

Class modifiers

---

CHANGELOG.md
lib/src/source_visitor.dart
test/whitespace/functions.unit
test/whitespace/metadata.unit
test/whitespace/switch.stmt

Also fix a couple of minor issues I noticed when testing against the Dart SDK repo:
- Gracefully handle empty switch expressions.
- Handle sync* and async* functions with => bodies.

Format metadata on patterns in for loops.

---

CHANGELOG.md
pubspec.yaml

Fixes https://github.com/dart-lang/dart_style/issues/1186

Release 2.2.5 to support bare libraries

---

CHANGELOG.md
pubspec.yaml

Bump pre-release version to 2.3.0-dev
Fix changelog for 6d19435c789e07cf1aaa29da019010b002882d39

Merge v2.2.5 with master

---

pubspec.yaml
tool/change_metrics.dart

This script is never user-facing, so its quality doesn't matter that much. But I want it to be committed to the repo that it lives somewhere outside of my machine.

Metrics script

---

.github/workflows/test-package.yml
CHANGELOG.md
lib/src/source_visitor.dart
pubspec.yaml
test/regression/0100/0108.unit
test/regression/1200/1249.unit

Fix #1249.
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
cc @brianquinlan

Fix regression in splitting type annotations with library prefixes.

---

CHANGELOG.md
pubspec.yaml

(I forgot to do this when I merged the first new IR PR onto main.)

Bump pubspec now that there are unpublished changes.

---

lib/src/back_end/code_writer.dart
lib/src/front_end/ast_node_visitor.dart
lib/src/front_end/piece_factory.dart
lib/src/piece/assign.dart
lib/src/piece/block.dart
lib/src/piece/if.dart
lib/src/piece/list.dart
lib/src/piece/sequence.dart
test/statement/if.stmt
test/statement/return.stmt

I also tweaked the CodeWriter API to make it easier to update the indentation when inserting a newline. This doesn't do anything radically new, but makes the piece formatting code a little shorter.
Made a field in SequencePiece private that didn't need to be public.

Format if and return statements.

---

lib/src/back_end/solver.dart

Noticed this while working on some other stuff and wanted to fix it before I forgot.

Fix some mistakes in the Solver doc comment.

---

lib/src/front_end/ast_node_visitor.dart
test/expression/assignment.stmt

This one was pretty straightforward since it uses the same logic as variable declarations.

Format assignment expressions.

---

lib/src/front_end/ast_node_visitor.dart
test/expression/prefix.stmt

Format prefix operators.

---

lib/src/front_end/ast_node_visitor.dart
test/statement/other.stmt
test/statement/other_comment.stmt

Small CL for yield behaviour.
No tests were migrated (but also, none existed for the temp dir lol), just added some simple ones.

Format yield and yield*.

---

lib/src/front_end/ast_node_visitor.dart
lib/src/front_end/piece_factory.dart
test/declaration/extension.unit

This was trivial thanks to `createType()`.

Format extensions.

---

example/format.dart
lib/src/front_end/ast_node_visitor.dart
lib/src/front_end/piece_factory.dart
lib/src/piece/function.dart
test/declaration/typedef.unit
test/declaration/typedef_comment.unit

I also resurrected the example code used for debugging that was inadvertently deleted by 624919455856244dff90124221694423dc7fcf9c.

Format typedefs.

---

lib/src/front_end/ast_node_visitor.dart
test/declaration/native.unit

Format native methods.

---

lib/src/front_end/ast_node_visitor.dart
test/pattern/cast.stmt
test/pattern/cast_comment.stmt

Quick pattern :)
Added some extra tests for comments and splitting, just in case. Seems simple enough.

Format cast pattern.

---

lib/src/piece/assign.dart

The underlying logic is the same, but I think this is a little easier to understand what's going on.

Simplify AssignPiece.

---

benchmark/directory.dart

I'm trying to get performance data on formatting real-world codebases, so this repeatedly runs the formatter on a given directory of Dart files.

Add a utility script for benchmarking and profiling a directory.

---

test/tall/regression/1000/1010.unit
test/tall/regression/1000/1029.unit

Migrate regression/1000/

---

test/tall/regression/0800/0802.unit
test/tall/regression/0800/0831.unit
test/tall/regression/0800/0837.unit
test/tall/regression/0800/0855.unit
test/tall/regression/0800/0862.unit
test/tall/regression/0800/0869.stmt
test/tall/regression/0800/0881.unit
test/tall/regression/0800/0888.unit

Migrate regression/0800/

---

.github/workflows/test-package.yml
CHANGELOG.md
lib/src/front_end/ast_node_visitor.dart
lib/src/front_end/piece_factory.dart
lib/src/short/source_visitor.dart
pubspec.yaml

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- …

Require analyzer 6.5.0 and stop using deprecated nodes.

---

lib/src/back_end/solution.dart

A key optimization in the new formatting is formatting entire branches of the piece tree separately and then merging in the results. This lets us reuse the results of solving and formatting that subtree across multiple solutions.
When merging the results back, it's important that the resulting solution has the same cost and other metrics as if the subtree had not been formatted separately. Otherwise, the optimization can change the formatting behavior.
When I first implemented subtree merging, I ran into some issues where it seemed like the resulting cost wasn't right. I wasn't able to figure out exactly why. To fix it, I made sure we didn't double count the cost of any given bound piece by merging each piece state in the subtree back into the parent solution and only counting its cost if …

Simplify subtree merging.

---

test/tall/regression/1400/1463.unit

Fix #1463. (The new formatter is already doing a good job on this code.)

Add regression test for #1463.

---

lib/src/front_end/sequence_builder.dart
test/tall/top_level/whitespace.unit

(Strangely, yes, I found several of these in the wild on pub.)

Don't crash when formatting an empty source file.

---

lib/src/front_end/piece_factory.dart

Applying your suggestion from the PR.

Change firstWhereOrNull() to nonNulls.firstOrNull.

---

lib/src/front_end/piece_factory.dart

I'm not sure how neither my IDE nor CI caught this.

Remove an unused import.

---

test/tall/regression/0600/0624.unit

This is doing what users want in the new tall style. \o/
Close #624.

Add regression test for #624.

---

benchmark/case/curry_2.expect
benchmark/case/curry_2.expect_short
benchmark/case/curry_2.unit
test/tall/regression/1500/1521.unit

The new style formats this about 200x faster than the old one. It's still kind of slow, but tolerable.
Fix #1521.

Add benchmark and regression test for #1521.

---

test/tall/regression/1600/1628.unit

Looks like this was already fixed by #1615.
Close #1628.

Add regression test for #1628.

---

CHANGELOG.md
lib/src/cli/formatter_options.dart
pubspec.yaml

It's already rolled into the SDK and google3.

Bump version number to publish 3.0.1.

---

test/tall/regression/0900/0900.stmt
test/tall/regression/1500/1525.stmt
test/tall/regression/1500/1526.stmt
test/tall/regression/1500/1526.unit
test/tall/regression/1600/1603.stmt
test/tall/regression/1600/1685.stmt

(Most were fixed by #1687, but some were already better.)
Close #900 (!).
Close #1525.
Close #1526.
Close #1603.
Close #1685.

Add regression tests for issues that are fixed now.

---

test/tall/regression/1600/1645.unit

This is already fixed (probably by #1687).
Close #1645.

Add regression test for #1645.

---

test/tall/regression/1700/1712.unit

This was already fixed by #1687.
Close #1712.

Add regression test for #1712.
