lib/src/source_visitor.dart, pubspec.yaml
We plan on removing deprecated APIs as part of the next breaking change of analyzer, and dart_style is using one of those APIs. This PR proactively replaces the use of the API. (In other words, this isn't urgent.) Unfortunately, this requires narrowing the version constraints on analyzer.
I'm not sure how to handle the pubspec.lock file in a situation like this. Guidance welcome.
Also, there is a strong-mode error being reported. I'd be happy to fix it, either as part of this PR or separately. Let me know if you'd like me to do that.
=> Replace use of deprecated API

lib/src/dart_formatter.dart, lib/src/source_visitor.dart, test/splitting/constructors.unit, test/whitespace/constructors.unit, test/whitespace/functions.unit
- "=" as separate for named optional parameters. This was conveniently
already doing the right thing.
- Asserts in constructor initializers. This was broken. :( Fixed it.
This patch works, but the tests don't pass unless you use an unreleased
version of analyzer. So, for now this won't be merged in until after
that's released and I upgrade the pubspec in this branch.
=> Add tests for new language features:

test/formatter_test.dart, test/utils.dart
Uri.toFilePath() rather than Uri.path should be used.
=> Update tests to use correct Windows file paths

CHANGELOG.md, bin/format.dart, example/format.dart, lib/src/call_chain_visitor.dart, pubspec.lock, pubspec.yaml, test/regression/0500/0582.unit
=> Don't drop type argument on method calls with closure arguments.

lib/src/chunk_builder.dart, lib/src/rule/type_argument.dart, pubspec.lock, pubspec.yaml, test/regression/0500/0584.unit, test/splitting/generic_method_parameters.unit
=> Fix splitting in generic methods with "=>" body.

CHANGELOG.md, lib/src/argument_list_visitor.dart, test/regression/0500/0500.unit
=> Handle mixed block and arrow bodied function arguments uniformly.

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0500/0543.unit, test/regression/0500/0589.unit, test/splitting/type_arguments.stmt
=> Don't split after '<' when a collection is in statement position.

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0500/0571.unit, test/whitespace/metadata.unit
=> Preserve a blank line between an annotation and the first directive.

CHANGELOG.md, lib/src/source_visitor.dart, test/whitespace/cascades.stmt
=> Force a split if the cascade target has non-obvious precedence.

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0500/0543.unit, test/regression/0500/0591.unit, test/splitting/invocations.stmt, test/whitespace/cascades.stmt
This makes cascades more similar to method calls and other syntax where
a split in a subexpression forces the outer expression to split. So,
instead of:
method(argument,
another)..cascade();
This produces:
method(argument,
another)
..cascade();
Fix #591.
=> Split the cascade (usually) if the cascade target contains a split.

lib/src/source_visitor.dart, test/whitespace/cascades.stmt
The previous change was a little too aggressize and turned code like:
[1, 2, 3, 4, 5, 6]
..addAll([7, 8, 9]);
Into:
[
1,
2,
3,
4,
5,
6
]..addAll([7, 8, 9]);
=> Tweak the rules for when a cascade splits a little more.

CHANGELOG.md, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/splitting/function_types.unit, test/whitespace/function_types.unit, test/whitespace/metadata.unit
=> Support new generic function typedef syntax.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0600/0613.unit, test/splitting/generic_method_parameters.unit, test/whitespace/functions.unit
=> Don't drop type arguments on generic function typed parameters.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.yaml, test/splitting/function_types.unit, test/splitting/part.unit, test/whitespace/directives.unit, test/whitespace/function_types.unit
=> Support URIs in part-of directives.

CHANGELOG.md, lib/src/source_visitor.dart, pubspec.yaml
Minor fix. Something I bumped into while integrating the fasta scanner into analyzer.
=> replace .toString() with .lexeme

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.lock, test/splitting/constructors.unit
=> Support assert in initializer list experiment.

CHANGELOG.md, lib/src/argument_list_visitor.dart, lib/src/chunk.dart, lib/src/source_visitor.dart, test/splitting/strings.stmt
Closes #570
Note that I'm not wedded to the nomenclature here at all.
=> Format multiline strings as block arguments.

pubspec.yaml
Partial towards https://github.com/dart-lang/dart_style/issues/638.
This is important because `dart_style` is used as a `dependency` in a few packages (think code-generation), and limiting `args` makes developing them (and using newer features) much harder.
=> Bump use of pkg/args to <2.0.0.

CHANGELOG.md, bin/format.dart, pubspec.lock, pubspec.yaml
Getting ready to release 1.0.9.
The only change in it is your removal of scheduled_test (which is an excellent change :) ).
=> Bump to 1.0.9.

pubspec.lock, test/whitespace/type_arguments.stmt
=> Add tests for generalized void (which appears to already work fine).

CHANGELOG.md, bin/format.dart, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/whitespace/type_arguments.stmt
In almost all cases, an elided "new"/"const" is parsed as a normal
method call by analyzer, so the existing formatting behavior for those
does the right thing. The only edge case is a named constructor on a
generic class. That syntax can *only* be a constructor call, so it's
parsed as an instance creation expression.
When we get to that code path, we need to not add an extra space before
the class name if there is no preceding "new" or "const" keyword.
Fix #652.
=> Support optional new/const.

CHANGELOG.md, lib/src/call_chain_visitor.dart, test/regression/0500/0548.stmt, test/regression/0600/0665.stmt, test/splitting/invocations.stmt, test/splitting/list_arguments.stmt, test/splitting/map_arguments.stmt
=> Don't split before "." when the target has a trailing comma.

lib/src/source_visitor.dart, test/regression/0600/0658.unit, test/splitting/constructors.unit
This gets avoids the pointless newlines of the old formatting rules,
but keeps it otherwise closer to the original behavior than
43832d24e7b86a165ec6a1765cbbb3644cae5f38 does.
In particular, initialization lists are always indented +6. This ensures
that initialization lists line up for constructors with trailing commas,
without, with optional parameters, mandatory, or none at all.
=> Tweak how initialization lists are handled after trailing commas.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0600/0680.stmt, test/splitting/statements.stmt
=> Force split in empty blocks in if statements with else clauses.

CHANGELOG.md, README.md, bin/format.dart, lib/dart_style.dart, lib/src/dart_formatter.dart, lib/src/formatter_options.dart, lib/src/io.dart, lib/src/source_visitor.dart, lib/src/style_fix.dart, pubspec.yaml, test/command_line_test.dart, test/fix_test.dart, test/fixes/named_default_separator.unit, test/formatter_test.dart, test/utils.dart
Implement the first fix, converting ":" to "=" as the named default
value separator.
=> Add support for non-whitespace opt-in "style fixes".

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/fixes/optional_new.stmt, test/regression/0000/0057.stmt, test/regression/0100/0189.stmt, test/regression/0200/0226.stmt, test/regression/0400/0467.unit, test/regression/0500/0500.unit, test/regression/0700/0707.stmt, test/regression/other/analysis_server.unit, test/splitting/strings.stmt, test/utils.dart, test/whitespace/expressions.stmt
If it ever ends up splitting inside an interpolation, it looks pretty
gnarly, but that's mostly a signal to the user to split up the string.
It does nicely clean up the whitespace.
More importantly, this means fixes apply inside interpolation too.
Fix #226. Fix #707.
=> Reformat expressions inside interpolated expressions.

CHANGELOG.md, bin/format.dart, lib/src/chunk_builder.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0000/0057.stmt, test/regression/0100/0189.stmt, test/regression/0400/0467.unit, test/regression/0500/0500.unit, test/splitting/strings.stmt
When it happens, it's usually a sign that you should split the string
yourself to avoid it. But it still looks terrible. And in multi-line
strings, you may *want* to have lines longer than the page width, in
which case the splitting is really bad.
=> Don't split inside string interpolation.

lib/src/error_listener.dart
The fasta parser produces some semantic errors (e.g. final variable not initialized) which the dart formatter can safely ignore.
=> Ignore all non syntactic errors

test/whitespace/metadata.unit
This test case is invalid Dart syntax that the old analyzer parser let slide by.
From the end of section 9.2.1 of the language spec
> It is a compile-time error if the modifier covariant occurs on a parameter of a function which is not an instance method, instance setter, or instance operator.
=> Update covariant modifier test

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0700/0720.unit
The visitMetadata() method is only used for metadata annotations on
members and some other things. visitAnnotation() is where all metadata
is handled.
Fix #720.
=> Handle all metadata annotations for optional "const".

lib/src/chunk_builder.dart, test/fixes/doc_comments.stmt
A line that didn't have a leading `*` but did have a `*` elsewhere in
the line would have everything before the `*` trimmed.
cc @lrhn
=> Add more tests for doc comment fix and fix an edge case.

lib/src/source_visitor.dart, lib/src/style_fix.dart, test/fix_test.dart, test/fixes/typedefs.unit
WDYT?
Would it be better to build a new node for the converted syntax and then visit that node, instead of physically building the output? It would ensure consistent formatting.
=> Add --fix-typedefs to Dart formatter.

lib/src/dart_formatter.dart, pubspec.lock, pubspec.yaml
Now that set literals are enabled by default, this is a step towards removing this feature's experimental flag from the analyzer/parser base.
=> remove enableSetLiterals flag

lib/src/argument_list_visitor.dart, lib/src/call_chain_visitor.dart, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/comments/sets.stmt, test/splitting/sets.stmt
As part of implementing the "UI as code" feature
(https://github.com/dart-lang/language/blob/master/accepted/future-releases/unified-collections/feature-specification.md)
the analyzer is deprecating the following classes and methods:
- ForStatement and ForEachStatement (ForStatement2 is now used for
both kinds of loops)
- ListLiteral.elements (use elements2, which has a more general return
type)
- AstVisitor.visitForEachStatement and AstVisitor.visitForStatement
(visitForStatement2 is now used for both kinds of loops)
- AstVisitor.visitMapLiteral and AstVisitor.visitSetLiteral
(visitSetOrMapLiteral is now used for both kinds of literals).
See deprecation CL: https://dart-review.googlesource.com/c/sdk/+/95665/
Analyzer clients need to be adapted to stop using the deprecated
classes and …
=> Stop using deprecated AST classes/methods.

lib/src/argument_list_visitor.dart, lib/src/dart_formatter.dart, lib/src/nesting_builder.dart, lib/src/source_visitor.dart, test/splitting/list_collection_if.stmt, test/splitting/lists.stmt, test/splitting/map_collection_if.stmt, test/splitting/maps.stmt, test/splitting/set_collection_if.stmt, test/splitting/sets.stmt, test/whitespace/collections.stmt, test/whitespace/expressions.stmt
(I'll do "for" in a separate commit.)
=> Formatting support for spread and if control flow elements.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/splitting/list_collection_for.stmt, test/splitting/map_collection_for.stmt, test/splitting/set_collection_for.stmt, test/whitespace/collections.stmt
This also includes the changes from #783 so (to make your life easier), please hold off on looking at this until that lands and I merge into this PR. I'll let you know when I have.
=> Collection for

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0100/0185.stmt, test/regression/0200/0211.unit, test/regression/0400/0467.unit, test/regression/0700/0705.stmt, test/regression/0700/0799.unit, test/regression/other/flutter.unit, test/whitespace/adjacent_strings.stmt
Fix #799. See the CHANGELOG diff for details. The relevant examples are:
1.2.4:
```dart
function(
"adjacent"
"string");
function(
"adjacent"
"string", // Not great.
);
function(
"adjacent"
"string",
"another");
function(
"adjacent"
"string",
"another",
);
```
1.2.5:
```dart
function(
"adjacent"
"string"); // Regression, but consistent with trailing comma.
function(
"adjacent"
"string",
);
function(
"adjacent"
"string", // Uintentional, but an improvement.
"another");
function(
"adjacent"
"string", // Unchanged.
"another",
);
```
Now:
```dart
function(
"adjacent"
"string"); // No indent, since not needed to distinguish args.
function(
"adjacent"
"string", // Consistent with non-trailing.
);
function(
"adjacent"
"string", // Intentional, distinguishes from next string.
"another");
function( …
```
=> Better indentation of adjacent strings in argument lists.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0400/0467.unit, test/regression/0800/0802.unit, test/whitespace/adjacent_strings.stmt
Fixes #802.
I ran it on a big corpus and compared to 1.2.6, the only changes are expected ones around these functions.
=> Don't indent adjacent strings directly inside "=>" functions.

lib/src/source_visitor.dart, test/splitting/function_arguments.stmt
Actual:
```dart
onTap: () {
Navigator.of(context).push(CupertinoPageRoute<void>(
title: colorName,
builder: (BuildContext context) => Tab1ItemPage(
color: color,
colorName: colorName,
index: index,
),
));
},
```
Expected:
```dart
onTap: () {
Navigator.of(context).push(CupertinoPageRoute<void>(
title: colorName,
builder: (BuildContext context) => Tab1ItemPage(
color: color,
colorName: colorName,
index: index,
),
));
},
```
=> no extra-indent of expression function as argument with trailing comma

CHANGELOG.md, lib/src/call_chain_visitor.dart, lib/src/dart_formatter.dart, pubspec.lock, pubspec.yaml, test/splitting/invocations.stmt, test/whitespace/expressions.stmt
In the process, I reorganized CallChainVisitor to more gracefully
handle the various combinations of selectors. It was getting a little
too hard to understand.
That also highlighted that we didn't have good support for invocation
expressions inside call chains. So I added better formatting for that
too.
=> Format null-assertion operators.

lib/src/source_visitor.dart
The AOT compiler does not currently compile regexes to machine code,
which makes them significantly slower. The regex in this function is
perf critical and makes the dart_style benchmark 65% slower on AOT than
on the JIT.
This fixes some of that regression.
Before:
```
// JIT
Best   : 4.93ms ========================
Best   : 4.83ms ========================
Best   : 4.80ms ========================
// AOT
Best   : 8.33ms =========================================
Best   : 8.43ms ==========================================
Best   : 8.37ms =========================================
```
After:
```
// JIT
Best   : 4.93ms ========================
Best   : 4.83ms ========================
Best   : 4.80ms ========================
// AOT
Best   : 6.93ms ==================================
Best   : …
```
=> Optimize _looksLikeClassName() in AOT builds.

test/splitting/expressions.stmt, test/splitting/invocations.stmt, test/whitespace/expressions.stmt
No code changes are needed since "?.[" is treated as a single token by
the parser and dartfmt just preserves the whole lexeme.
=> Add tests for null-aware index expressions.

test/whitespace/cascades.stmt
No code changes are needed because analyzer parses it as the same
expression, just with a different token lexeme.
=> Add tests for formatting "?..".

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0800/0831.unit, test/splitting/list_collection_if.stmt
Spread collection literals are given special block-like formatting to
produce output like:
```dart
[
if (condition) ...[
1,
2
]
]
```
This doesn't work for empty literals since they can't split inside.
Instead, we just don't give those block handling at all. That's maybe
not the ideal formatting -- there are cases where splitting the empty
collection would look better, but it works pretty well and is simple.
Fix #831.
=> Don't give empty spread collections block-like formatting.

CHANGELOG.md, lib/src/call_chain_visitor.dart, test/regression/0700/0704.unit, test/splitting/invocations.stmt
The method chain splitting logic allows "." to immediately follow some
targets, like collection literals:
[
element,
].forEach((_) => ...);
This extends that to allow parenthesized expressions:
([
element,
]).forEach((_) => ...);
Fix #704.
=> Don't force a split before "." on parenthesized targets.

pubspec.yaml
- Switch `analyzer` dep to caret style since it's a shorter way to
express the same constraint.
- Switch `args` dep to caret style since there are no earlier version
which also support the SDK used by this package.
=> Simplify dep version constraints

CHANGELOG.md, bin/format.dart, lib/src/call_chain_visitor.dart, pubspec.yaml, test/regression/0800/0855.unit
A _Selector gets assigned to a variable and field whose type was the
subclass _MethodSelector. However, sometimes the value is actually a
_PropertySelector. Alas, that unsafe downcast isn't caught at compile
time because of implicit downcasts. :(
Fix #855.
=> Fix crash on hanging property calls following block arguments.

pubspec.yaml, tool/grind.dart
- Remove `async` dep since it is unused.
- Use consistent single quotes for imports.
=> Fix inconsistencies after revert

CHANGELOG.md, bin/format.dart, lib/src/argument_list_visitor.dart, lib/src/call_chain_visitor.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0800/0862.unit, test/whitespace/functions.unit
Fix #862. This is a workaround for:
https://github.com/dart-lang/sdk/issues/38990
cc @leafpetersen
=> Preserve commas after nullable function-typed parameters.

lib/src/source_visitor.dart, lib/src/style_fix.dart
Automatically cleans up violations of the lint avoid_single_cascade_in_expression_statements.
Before:
```
o..m = x;
```
After:
```
o.m = x;
```
Adds parentheses when necessary to avoid changing operator precedence, as in the following examples:
Before:
```
a as A..x = 42;
```
After:
```
(a as A).x = 42;
```
Before:
```
await someFuture
..doThing();
```
After:
```
(await someFuture).doThing();
```
=> Add --fix-single-cascade-statements flag.

CHANGELOG.md, lib/src/chunk_builder.dart, test/fixes/doc_comments.stmt
This was done for comment lines starting with "`*`" but not ones without
the (correct) JavaDoc marker. Now it does so for doc comment lines that
lack a leading "`*`".
=> Preserve leading indentation in fixed doc comments (#821).

CHANGELOG.md, bin/format.dart, test/command_line_test.dart
Introduce the verbose flag into dart_style to make it consistent with other dart CLI that have this flag (`-v` / `--verbose`)
=> Introduce the verbose flag into dart_style 

pubspec.lock
We need to pick up version `2.2.0` of `http_multi_server` for
compatibility with a breaking change in the SDK.
https://github.com/dart-lang/sdk/issues/39657
=> Pub upgrade

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0900/0900.stmt, test/splitting/variables.stmt
This fixes the example in the second comment on issue #900, but not
the main issue.
=> Indent blocks in initializers of multiple variable declarations.

CHANGELOG.md, bin/format.dart, lib/src/cli/show.dart, pubspec.yaml, test/command_line_test.dart
That release contains a new separate hidden library for running the CLI.
The new library has a different command line interface, but the current
interface exposed by "dartfmt" should be unchanged. Unfortunately, I
accidentally broke that and running the formatter stopped showing the
names of files that were formatted or unchanged.
This restores that (and adds tests, which I thought already existed).
=> Restore the command line output inadvertently removed in 1.3.4.

pubspec.yaml, test/command_line_test.dart, test/command_test.dart, test/utils.dart
There are two test suites that spawn Dart executables to validate the
CLI behavior. Those are painfully slow when running the programs from
source. This precompiles them to native executes and then spawns those.
On my machine it takes the tests from ~4 minutes down to ~40 seconds.
(Also this should fix the failure when running the tests inside the SDK.)
=> Generate native executables to use when running the integration tests.

CHANGELOG.md, lib/src/cli/options.dart, test/command_line_test.dart, test/command_test.dart
The SDK bots found a few more things.
Most of the changes are in the tests themselves, but the one
user-visible change is that the default name shown in errors when
reading from stdin is now "stdin" instead of "<stdin>" since analyzer
tries to parse it as a file path and angle brackets aren't allowed on
Windows.
=> Fix test failures on Windows.

README.md
SDK was written as SDL in "Getting dartfmt"
=> Fixing a very small Typo in README.md

CHANGELOG.md, bin/format.dart, lib/src/cli/format_command.dart, lib/src/cli/options.dart, pubspec.yaml, test/command_line_test.dart, test/command_test.dart, tool/command_shell.dart
Makes the "dart format help" and error messages much easier on the eyes.
Fix #938.
cc @devoncarew
=> Add "--verbose" to "--help" and hide most options normally.

CHANGELOG.md, lib/src/string_compare.dart, test/command_line_test.dart, test/string_compare_test.dart, test/utils.dart, test/whitespace/trailing.unit, test/whitespace/unicode.unit
* Don't crash when trailing non-ASCII whitespace is trimmed.
* Add tests for trailing whitespace trimming.
* Add tests for other Unicode characters.
Fix #901.
=> Handle Unicode whitespace more gracefully.

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0900/0927.unit, test/splitting/expressions.stmt, test/whitespace/expressions.stmt
(Also cleaned up a TODO I noticed along the way.)
Fix #927.
=> Split conditional expressions when nested.

.travis.yml, CHANGELOG.md, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/splitting/members.unit, test/whitespace/classes.unit, test/whitespace/external.unit, test/whitespace/functions.unit, test/whitespace/metadata.unit
Fix #946.
The dependency_override is temporary. Once a version of test that I can use is published, I'll fix the pubspec here before I merge into master. I just wanted to get this out for review since the dart_style changes are done and working.
=> Format `external` and `abstract` on variables.

test/utils.dart
No longer needed since Dart 2.1 added Future/Stream to dart:core exports
=> Remove unused dart:async import

CHANGELOG.md, lib/src/cli/formatter_options.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/0900/0966.stmt
There was a bug where every "else" in a chained if element used the
first element's "else" token instead of its own. This had the
unfortunate side effect of duplicating any comment that appeared before
the first one (and discarding comments on the later ones).
Fix #966.
=> Don't duplicate comments on chained if elements.

lib/src/cli/options.dart
- add a type annotation to `defineOptions()`
This was missing a type annotation (but was likely intended to be `bool`) - you might consider adding the `type_annotate_public_apis` lint to the analysis options file.
=> add a type annotation to defineOptions()

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/line_splitting/rule_set.dart, lib/src/line_splitting/solve_state_queue.dart, pubspec.lock, pubspec.yaml
- Use FeatureSet.fromEnableFlags2() and pass in an explicit language
version. Hard-coding the language version is a little dubious, but
probably practically correct since dart_style is generally not
forward compatible with language changes.
- Stop using the deprecated List() constructor. This change technically
isn't needed until the null safety migration, but this addresses the
deprecate lint errors.
=> Fix uses of deprecated APIs.

CHANGELOG.md, lib/src/chunk_builder.dart, lib/src/source_visitor.dart, pubspec.yaml
The formatter pushed a rule before the initializer list but did not
pop it if there were no initializers. In that case, the rule stuck
around and got entangled with later rules that should be unrelated. This
caused a super-linear performance cost as a the file got larger.
=> Fix performance bug in constructors without initializer lists.

CHANGELOG.md, pubspec.lock, pubspec.yaml
This is required to unblock some elements of the ecosystem (namely, build and packages using it), allowing them to use new language features implemented only in analyzer 1.0.0 even if they aren't fully ported to null safety yet.
=> Update to latest version of analyzer

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.yaml, test/splitting/annotations.unit, test/whitespace/metadata.unit
This change provides enough support to avoid a crash and ensure that
generic annotations are preserved by the formatter.
We don't yet insert as many line breaks as we arguably should (see the
example in test/splitting/annotations.unit); we can improve that in a
future change.
=> Preliminary support for generic annotations.

pubspec.yaml
I'm going to publish this as a separate release so that users (like
dartdoc) who just want the latest analyzer and generic annotation
support can get it without having to deal with a major version bump to
2.0.0.
=> Bump to 1.3.14.

lib/src/call_chain_visitor.dart, lib/src/chunk.dart, lib/src/chunk_builder.dart, lib/src/debug.dart, lib/src/line_splitting/solve_state.dart, lib/src/source_visitor.dart, test/regression/other/null_safety.unit, test/splitting/invocations.stmt
There are basically three issues here:
- The debug library, which isn't part of the public API, could crash
when logging a chunk that wasn't fully initialized. Turned
NestingLevel from late back to nullable to fix this. This doesn't
affect users.
- The null safety migration introduced a crash when formatting blocks
inside string interpolation (why would someone do that?!). To fix
that, instead of returning null chunks, changed ChunkBuilder to
return dummy chunks. They end up getting discarded anyway.
- Cascaded index operators always crash. I need to investigate more, but
I think this bug may exist in the previous version of dart_style,
which is in the SDK. I'll look into that next.
=> Fix a couple of crashes I found when testing the migration on a corpus.

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/line_splitting/solve_state.dart, pubspec.lock, pubspec.yaml, test/splitting/mixed.stmt, test/whitespace/expressions.stmt
=> Support triple-shift operators.

lib/src/source_visitor.dart, test/regression/0400/0407.unit, test/regression/0900/0927.unit, test/splitting/expressions.stmt
Fixes #722
Don't indent ternary expressions that are in the else leg of another ternary. This change makes nested ternaries used as a series of `else if` statements much more readable.
This
```
String type = status == 'OK'
? 'notices'
: status == 'NO'
? 'warnings'
: status == 'BAD'
? 'errors'
: '';
```
instead of 
```
String type = status == 'OK'
? 'notices'
: status == 'NO'
? 'warnings'
: status == 'BAD'
? 'errors'
: '';
```
=> Don't indent nested ternaries

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/0400/0407.unit, test/regression/0700/0713.stmt, test/regression/0700/0722.stmt, test/regression/0900/0927.unit, test/splitting/expressions.stmt
This leaves the tests and commented out implementation in place in case
we decide to re-enable the change later, but it's too close to Dart 2.13
and I've heard too much negative feedback to push it out right now.
Fortunately, I haven't actually published 2.0.1 yet (I was waiting for it to roll smoothly into google3), so I've just made this part of that version.
=> Revert the change to flatten nested conditionals.

CHANGELOG.md, lib/src/chunk.dart, lib/src/chunk_builder.dart, lib/src/source_visitor.dart, pubspec.yaml, test/comments/classes.unit, test/comments/extensions.unit, test/comments/functions.unit, test/comments/statements.stmt, test/comments/top_level.unit, test/regression/0100/0178.unit, test/regression/0800/0837.unit, test/regression/other/block_comment.unit
A very subtle bug in the comment handling would cause a /* */ inline
comment to force the surrounding code to full split when not needed in
some cases.
This fixes that issue. It also slightly tweaks the formatting of code
containing inline block comments in some rare cases. In practice, the
only code I see affected by that is formatter tests. In the real world,
all affected code is related to the bug itself and is fixed by this
change.
Fix #837.
=> Don't unnecessarily split argument lists with block comments.

CHANGELOG.md, bin/format.dart, lib/src/cli/format_command.dart, lib/src/io.dart
It reads from stdin asynchronously. Before this fix, the FormatCommand
did not wait for that to complete before returning the exit code, so it
would return before stdin had been formatted and any parse error
detected.
Fix #1035.
=> Return correct exit code from FormatCommand when formatting stdin.

CHANGELOG.md, lib/src/cli/formatter_options.dart, lib/src/io.dart, pubspec.yaml
The tests for dart_style do not seem to trigger this bug, and I'm not
sure why not. But I can repro it in dartdev, and I have a test there
that will trigger the bug. So I'm going to push out this fix, roll it
into the SDK, and land the dartdev test with that roll.
=> Fix hang when reading from stdin.

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.yaml, test/splitting/mixed.stmt, test/splitting/type_arguments.stmt, test/whitespace/expressions.stmt
=> Format generic function references and constructor tear-offs.

CHANGELOG.md, lib/src/cli/formatter_options.dart, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml, test/splitting/mixed.stmt, test/splitting/type_arguments.stmt, test/whitespace/expressions.stmt
Fix #1051.
Thanks for dealing with my Git noob-ness. :)
=> Re-introduce constructor tear-off support and fix analyzer constraint.

README.md, lib/src/source_visitor.dart, lib/src/string_compare.dart, test/fixes/doc_comments.stmt, test/whitespace/methods.unit, tool/command_shell.dart
There are still a few in the repo, but they are in code that exists to
implement or test the legacy CLI. Those will go away when support for
that is fully removed from the package in a future change.
=> Remove outdated references to "dartfmt".

CHANGELOG.md, lib/src/argument_list_visitor.dart, test/splitting/arguments.stmt, test/splitting/function_arguments.stmt, test/splitting/list_arguments.stmt
I opted to add support for this while being minimally invasive to the
existing style and formatting. All existing code which does not have any
positional arguments after named ones retains its previous formatting.
For new argument lists that use positional arguments after named ones,
I try to mostly follow the existing style rules even though they can be
fairly complex. In particular, it will be pretty aggressive about
applying block-style formatting to function literals inside argument
lists even with named args anywhere. I think that's important to support
the main use case I know of for the feature which is trailing positional
closures like:
```dart
function(named: 1, another: 2, () {
block...
});
```
In argument lists using named args anywhere that don't have block
functions, it …
=> Formatting support for named arguments anywhere.

lib/src/source_visitor.dart, pubspec.lock, pubspec.yaml
Clients should not build AST manually like this. There is one right way to do this - parse.
I was able to move almost all clients off the `AstFactory`, and `dart_style` is the last one. Unfortunately I was not able to find any better solution than to provide such specialized internal API for it.
=> Stop using 'astFactory', use specialized internal API.

CHANGELOG.md, example/format.dart, lib/src/chunk.dart, lib/src/chunk_builder.dart, lib/src/debug.dart, lib/src/line_splitting/line_splitter.dart, lib/src/line_splitting/rule_set.dart, lib/src/line_splitting/solve_state.dart, lib/src/line_writer.dart, lib/src/rule/rule.dart, lib/src/source_visitor.dart, lib/src/whitespace.dart, pubspec.yaml, test/comments/classes.unit, test/comments/enums.unit, test/comments/expressions.stmt, test/comments/functions.unit, test/comments/statements.stmt, test/fixes/function_typedefs.unit, test/fixes/optional_new.stmt, test/regression/other/chunk_refactor.unit, test/splitting/classes.unit, test/splitting/list_arguments.stmt, test/whitespace/adjacent_strings.stmt, test/whitespace/strings.stmt
The internal representation that the formatter users is a series of
chunks of code that can't contain any internal line breaks separated by
information describing the split between each one:
.----. .-----. .----. .-----. .----. .-----.
... |text| |split| |text| |split| |text| |split| ...
'----' '-----' '----' '-----' '----' '-----'
To have a homogeneous list of objects, each text/split pair is wrapped
into a single Chunk class. For historical reasons, they were paired up
so that each  Chunk has the text and the split that follows it:
.--------------. .--------------. .--------------.
|    Chunk     | |    Chunk     | |    Chunk     |
|.----. .-----.| |.----. .-----.| |.----. .-----.|
... ||text| |split|| ||text| |split|| ||text| |split|| ...
|'----' '-----'| |'----' '-----'| |'----' …
=> Refactor Chunk to represent the split preceding the chunk's text.

lib/src/argument_list_visitor.dart, lib/src/ast_extensions.dart, lib/src/call_chain_visitor.dart, lib/src/source_visitor.dart
These were mostly arbitrarily defined in SourceVisitor and that class
is huge enough as it is, so this moves them out.
=> Move a bunch of functions on AST nodes over to extensions.

CHANGELOG.md, lib/src/ast_extensions.dart, lib/src/chunk_builder.dart, lib/src/source_visitor.dart, test/comments/classes.unit, test/comments/extensions.unit
For mostly historical reasons, SourceVisitor used to create a flat list
of Chunks for some brace-delimited bodies like block statements and
switch bodies while using nested BlockChunks for function expression
bodies.
This now uniformly uses nested blocks for all of them. The visible
behavior is mostly unchanged except in a rare corner case with type
bodies containing only inline block comments where the old formatter
would arbitrarily split in one case but not the other. Now its behavior
is more consistent.
=> Simplify and unify how delimited bodies are handled.

lib/src/chunk.dart, lib/src/chunk_builder.dart, lib/src/debug.dart, lib/src/line_splitting/solve_state.dart, lib/src/line_writer.dart, lib/src/source_visitor.dart, test/comments/classes.unit, test/comments/enums.unit, test/comments/extensions.unit, test/comments/functions.unit, test/comments/lists.stmt, test/comments/maps.stmt, test/comments/sets.stmt, test/comments/statements.stmt, test/whitespace/classes.unit, test/whitespace/enums.unit, test/whitespace/extensions.unit, test/whitespace/methods.unit
Given a piece of code like:
main() {
a();
b();
}
There are top level chunks for `main() }` and `}`, and the chunks for
`a()` and `b()` are children.
Previously, the code stored those child chunks in the preceding parent
chunk (so `main() {` here). But it's the subsequent chunk (`}`) that
determines whether the block contents are actually split, so that
doesn't make a lot of sense and leads to weird `+ 1` and `- 1` when
working with nested chunks.
This refactors the code so that child chunks are stored on the same
chunk that determines whether or not they split. This means that chunks
are now written in a post-order traversal: a block chunk's children come
before its own text.
Since we now know that a chunk will have children at the moment that
it's created, removed the old ChunkBlock …
=> Refactor how child chunks are stored.

lib/src/rule/argument.dart
I didn't notice until after I sent out the last refactoring that
NamedRule doesn't use these fields at all so there's no reason for them
to be in the base class.
=> Move collection argument counts from ArgumentRule to PositionalRule.

analysis_options.yaml, example/format.dart, pubspec.lock, pubspec.yaml, test/utils.dart
Fix new lints
Remove explicit lints that are added to lints v2
=> Require the latest version of pkg:lints

.github/workflows/test-package.yml, CHANGELOG.md, lib/src/cli/formatter_options.dart, lib/src/source_visitor.dart, pubspec.yaml
Since one of the deprecations is moving `.name2` _back_ to `.name`, I think it's necessary to bump the lower bound. In analyzer 4.4.0, `.name` may have meant a different thing...
In any case, analyzer 5.1.0 is the first release to allow unnamed libraries, so I think it is necessary for the follow up PR which adds such support in dart_style.
=> Bump to analyzer 5.1.0 and handle deprecations

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, test/comments/top_level.unit, test/whitespace/directives.unit
=> Format unnamed libraries

lib/src/cli/options.dart
Towards #1115
This is option is not intended to be user facing. It is not ergonomic, and it causes confusion in the current state. The option is not removed because it is used for tests, and we don't want to break scripts which are passing the option today.
=> Hide the --line-length option

CHANGELOG.md, lib/src/source_visitor.dart
Using `dynamic` did not report using `name2`, so my attempt to pull `dart_style` into SDK and remove the deprecated methods failed. To prevent this in the future, I think it is better to use more types.
=> Use typed _visitFunctionOrMethodDeclaration(), stop using 'name2'.

CHANGELOG.md, test/whitespace/metadata.unit
With records coming, we use whitespace there to disambiguate metadata annotation arguments from a subsequent record type annotation. There was a metadata formatting test whose before code had whitespace there and now will be interpreted differently (and erroneously) by the language. This fixes that test.
Note that there are no changes to the formatter itself. It's just a formatting test whose "before" code is a little too wild with the whitespace. :)
cc @jensjoha
=> Fix a metadata test to not have whitespace before the "(".

lib/src/source_visitor.dart
I believe the *intent* of these constraints is that if a parameter list splits then the metadata before each parameters split too. With these, instead of:
```dart
function(
@anno param,
@anno param,
@anno param) {
```
Where the parameters can split while leaving the annotations alone, the annotations are forced to split too:
```dart
function(
@anno
param,
@anno
param,
@anno param) {
```
But...
1. These constraints don't appear to do that.
2. There are no tests that they would do that. In fact, all the tests pass with these lines removed.
3. And when I format a large corpus with these lines removed, there are no differences versus when them included. They don't appear to do anything.
4. Most importantly, it seems that the current style is to allow a parameter list to split while keeping …
=> Remove non-working constraint between metadata and parameters.

CHANGELOG.md, lib/src/argument_list_visitor.dart, lib/src/ast_extensions.dart, lib/src/dart_formatter.dart, lib/src/line_writer.dart, lib/src/source_visitor.dart, test/comments/records.stmt, test/regression/other/analyzer.unit, test/splitting/annotations.unit, test/splitting/function_types.unit, test/splitting/record_types.unit, test/splitting/records.stmt, test/whitespace/expressions.stmt, test/whitespace/record_types.unit, test/whitespace/type_arguments.stmt
In the process of working on this, I discovered that multi-line function types with trailing commas are pretty busted looking. (I guess no one puts trailing commas there.) I fixed those too, since they are structurally similar to record types in many ways.
(If you don't have time to review this, @natebosch, feel free to bounce it to someone else.)
=> Format records and record type annotations.

lib/src/dart_formatter.dart, lib/src/source_visitor.dart, test/comments/patterns.stmt, test/splitting/if_case.stmt, test/splitting/list_collection_if.stmt, test/splitting/patterns.stmt, test/whitespace/if.stmt, test/whitespace/patterns.stmt
I'm breaking this up into a series of PRs so it's not overwhelming. Also, I'm going to merge these PRs into a separate "patterns" branch until #1164 is resolved. That way, master isn't broken.
This first PR:
- Enables parsing patterns.
- Does some rudimentary formatting of constant patterns so that the existing switch tests don't break. I'll add more tests for constant patterns in a later PR.
- Formats if-case statements and elements.
- Formats logic, relational, and parenthesized patterns.
=> Start formatting patterns and other related syntax.

lib/src/source_visitor.dart, test/comments/patterns.stmt, test/splitting/patterns.stmt, test/whitespace/patterns.stmt
That means unary and primary patterns, but excludes all of the delimited
ones: list, map, record, object and the corresponding constants.
=> Format the remaining simple patterns.

lib/src/debug.dart
A while back, I did a big refactoring where each Chunk's split now describes the line split before that Chunk's text instead of after. When I did that, it looks like I didn't update how the debug output draws spans.
Since this is only used for debugging the formatter, it doesn't affect users. But it make for some very confusing debugging for me.
=> Fix how spans are rendered in the debug output.

lib/src/cli/show.dart
If you run bin/format.dart, it prints:
Formatting directory Closure: (String) => void from Function 'directory':.:
Which is obviously not right. :) This fixes that.
Almost no one with notice this because `dart format` goes through the new CLI and doesn't use this entrypoint. But if you global activate the dart_style package or use `dart pub run` to get to the old entrypoint you might see it.
=> Fix the directory path shown by the old CLI.

CHANGELOG.md, lib/src/argument_list_visitor.dart, lib/src/source_visitor.dart, pubspec.yaml, test/comments/patterns.stmt, test/regression/other/misc.unit, test/splitting/list_arguments.stmt, test/splitting/map_arguments.stmt, test/splitting/patterns.stmt, test/splitting/records.stmt, test/splitting/sets.stmt, test/splitting/type_arguments.stmt, test/whitespace/patterns.stmt
Also test list, map, set, and record constants inside patterns.
In the process of working on this, I noticed that the formatting for collection literal type arguments isn't ideal. In rare cases, it would split after the initial "<", which looks totally broken. I fixed that here too. I'd normally pull that out into a separate PR but it's mixed in with the other changes to _visitCollectionLiteral() so that would be hard.
Also added some more tests around avoiding splitting between a named argument and a subsequent collection literal. The code was there to handle it but it wasn't tested well. (It's hard to come up with an example that hits that exact code path without formatting correctly for other reasons.)
=> Format list, map, and record patterns.

lib/src/source_visitor.dart, test/comments/patterns.stmt, test/splitting/arguments.stmt, test/splitting/patterns.stmt, test/whitespace/patterns.stmt
The latter two were already implemented as part of keeping the existing switch tests passing, but this adds tests for their splitting and other behavior.
For object patterns, I had to decide whether to split them like collections (like other patterns) or like argument lists (which they mirror). I went collection-like because they will appear mixed with other patterns. Also, if we migrate to a consistent flutter-like style at some point, it will be one less thing to change.
Let me know what you think.
=> Format object patterns, const constructors, and constant expressions.

CHANGELOG.md, benchmark/after.dart.txt, benchmark/before.dart.txt, lib/src/chunk_builder.dart, lib/src/rule/argument.dart, lib/src/rule/rule.dart, lib/src/source_visitor.dart, test/comments/switch.stmt, test/splitting/switch.stmt, test/whitespace/metadata.unit, test/whitespace/patterns.stmt
In the previous PR, any case body that fit on one line was allowed to even if other cases in the same switch didn't. I tested it on a corpus and I found that led to confusing switches where it wasn't always clear where the case body starts.
I think you really want it all or nothing: either every single case fits on the same line in which case you can make the whole switch compact, or every case should be on its own line, even the ones that would fit.
Unfortunately, it's a little tricky to have formatter rules that span code containing hard splits, so getting that working took some doing. It also regressed performance pretty badly. But I figured out some optimizations in ChunkBuilder and it's basically back to the same performance it had before.
Also, this incidentally fixes a bug where …
=> Better style for inline case bodies.

test/comments/switch.stmt
I spent a bunch of time investigating whether comments in switches that aren't inside a case body (i.e. not between the "case" line and some statement inside the case) should be indented to align with the cases or the bodies.
After trying a bunch of alternatives and running them on a big corpus, I concluded that the current behavior (always align to the cases) actually works very well in almost all real-world code. But it's not pinned down well by tests, so this does that.
=> Add some more tests to pin down comment indentation in switches.

lib/src/chunk.dart, lib/src/chunk_builder.dart, lib/src/dart_formatter.dart, lib/src/debug.dart, lib/src/source_visitor.dart, pubspec.yaml, test/comments/functions.unit, test/comments/switch.stmt, test/regression/1100/1181.stmt
In the process, I came up with a cleaner and faster solution for handling rules that span hard splits.
Fix #1181.
=> Don't crash on switches with empty trailing cases.

.github/workflows/test-package.yml, pubspec.yaml
Analyzer 5.7.0 is using dart:io classes which were added in 2.19.
=> Bump SDK used by GitHub Actions to 2.19

CHANGELOG.md, lib/src/source_visitor.dart, test/comments/switch.stmt, test/regression/1100/1181.stmt, test/regression/1100/1190.unit, test/splitting/switch.stmt, test/whitespace/patterns.stmt, test/whitespace/switch.stmt
I'm still interested in supporting this, but it causes a lot of churn. That means it really needs to go through the full dart style change process. Given how many other things are in the air with Dart 3.0, it seems like now is probably not the ideal time for that.
So, for now, I think we should keep the old formatting where case bodies always go on their own line.
cc @natebosch @iinozemtsev
=> Remove support for compact switch statements.

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.yaml, test/whitespace/classes.unit
Quick and dirty draft of the support. Currently we can't access `inlineToken` because public AST API does not expose it. 
We need [this CL](https://dart-review.googlesource.com/c/sdk/+/286180) to land first and then publish analyzer. Once that happens I will bump analyzer version in pubspec and convert this draft PR into a proper PR. 
/cc @munificent 
Fixes #1129
=> Enable support for inline class syntax

CHANGELOG.md, lib/src/cli/options.dart, pubspec.yaml, test/command_line_test.dart, test/command_test.dart
This doesn't completely fix #1153 because the command is still there and supported, but it's a step towards deprecating it.
=> Hide "--fix" and related options in help output.

CHANGELOG.md, lib/src/source_visitor.dart, test/regression/1100/1197.unit, test/splitting/arrows.stmt, test/splitting/switch.stmt, test/splitting/switch_expression.stmt
This makes them all line up as if they were empty cases in a switch statement, which is essentially how they behave. Instead of:
```dart
e = switch (obj) {
constant1 ||
constant2 ||
constant3 =>
body
};
```
Gives:
```dart
e = switch (obj) {
constant1 ||
constant2 ||
constant3 =>
body
};
```
This addresses some of the bad formatting in #1197. The rest is #1202.
cc @mit-mit
=> Don't indent outermost "||" pattern operands in switch expression cases.

CHANGELOG.md, lib/src/ast_extensions.dart, lib/src/source_visitor.dart, test/whitespace/cascades.stmt
This is consistent with how other collection literals preceding single-section cascades are formatted.
=> Don't split cascades on record literals.

CHANGELOG.md, lib/src/argument_list_visitor.dart, test/regression/1200/1205.stmt, test/splitting/records.stmt
This is consistent with how other collection literals are formatted in argument lists.
I originally made the formatting diverge deliberately because I felt it would make it clearer when you're looking at a record versus a series of arguments. But based on the thumbs up on:
https://github.com/dart-lang/dart_style/issues/1205
It appears that users prefer the more consistent formatting. In retrospect, I think I do too.
=> Give record expressions block-like formatting in argument lists.

lib/src/chunk.dart, lib/src/line_splitting/solve_state.dart, lib/src/line_splitting/solve_state_queue.dart, lib/src/marking_scheme.dart, lib/src/nesting_level.dart
I noticed that formating the file "pkg/front_end/lib/src/fasta/fasta_codes_cfe_generated.dart" from the dart sdk was quite slow, took a look into it and made some changes.
It's still quite slow, but at least it's better.
I've:
- Updated _compareScore to "cache" the costs and inlined the `compareTo` call (the sdk version takes a num and don't know it's already been compared to 0).
- Replaced the usage of Set in a few places with markings on the actual classes.
My measured runtimes:
```
AS-IS
Formatted 1 file (0 changed) in 3.53 seconds.
Formatted 1 file (0 changed) in 3.65 seconds.
Formatted 1 file (0 changed) in 3.64 seconds.
Formatted 1 file (0 changed) in 3.70 seconds.
Formatted 1 file (0 changed) in 3.85 seconds.
Formatted 1 file (0 changed) in 3.70 seconds.
Formatted 1 file (0 …
```
=> Optimize certain operations

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml
This is what's shipping in the next stable SDK, so we should get a version out for people using it as a library too.
=> Get ready to publish 2.3.1.

CHANGELOG.md, lib/src/source_visitor.dart, pubspec.yaml, test/comments/switch.stmt, test/regression/1200/1215.stmt
=> Don't force split on a line comment before a switch expression case.

CHANGELOG.md, lib/src/ast_extensions.dart, lib/src/call_chain_visitor.dart, lib/src/source_visitor.dart, pubspec.yaml, test/regression/1200/1213.unit, test/splitting/invocations.stmt
=> Don't split before `.` following a record literal.

CHANGELOG.md, lib/src/chunk_builder.dart, lib/src/source_visitor.dart, pubspec.yaml, test/comments/functions.unit, test/regression/0200/0247.unit, test/regression/0300/0387.unit, test/regression/0400/0444.unit, test/regression/1200/1212.unit, test/whitespace/metadata.unit
Also, don't indent parameters with metadata annotations.
Before this change, the formatter indents any parameter that contains metadata annotations that end up splitting:
function(
@required
int n,
@Deprecated('Some long deprecation string.')
String s) {
...
}
It also treats all parameters in a parameter list as a unit when deciding how to split their metadata. If any annotation in any parameter splits, then they all do. That's why there's a split after `@required` in the above example.
The intent of both of these is so that a parameter with unsplit metadata doesn't get confused for an annotation on the next parameter:
function(
@first('some string') int n,
@second('another string forces a split')
String s) {
...
}
Note here that there are two parameters, `n`, and `s`, and not just a …
=> Split metadata on parameters independently.

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/source_visitor.dart, pubspec.yaml
This PR requires `analyzer 5.12.0` and higher, and stops using deprecated APIs.
---
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Many Dart repos have a weekly cadence for reviewing …
=> Use analyzer 5.12, fix uses of deprecated APIs.

test/regression/0100/0108.unit
I failed to notice that with my previous PR this test started to fail.
Does it look as a reasonable change in formatting to you?
---
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing). …
=> Update expectations for 0108

CHANGELOG.md, lib/src/source_visitor.dart, test/whitespace/record_types.unit
=> Don't drop "?" on nullable empty record types.

.github/workflows/publish.yml, CHANGELOG.md
This adds the worflow I talked about before - I think its worth trying out and you can always remove it if you want. You will also need to enable automated publish in the pub admin page https://pub.dev/packages/dart_style/admin.
See https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose#integrating-this-tool-into-a-repo
Note that if you ever need to publish from a dev/beta SDK then we would want to require that sdk, see https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose#publishing-from-a-specific-version-of-the-sdk. Happy to add that config if you think it is necessary.
=> add firehose workflow

.github/dependabot.yml
- add a daily dependabot check for major version bumps
Dependabot PRs from this config may not be something that we can land directly (won't update changelog entries or package versions) but will give us awareness when there's a new major version of a dep available; that's particularly important for this package and package:analyzer.
---
<details>
- Most changes should add an entry to the …
=> add a daily dependabot check for major version bumps

CHANGELOG.md, lib/src/source_visitor.dart, pubspec.yaml, test/whitespace/classes.unit
That isn't the syntax we're going with and this will let the analyzer team change the AST API.
Fix #1241.
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
cc @oprypin
=> Remove support for `inline class`.

CHANGELOG.md, lib/src/cli/format_command.dart, lib/src/cli/formatter_options.dart, lib/src/cli/options.dart, lib/src/dart_formatter.dart, lib/src/io.dart, pubspec.yaml, test/command_test.dart
=> Stop passing experiment flags to parser for features that have shipped.

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml
I want to kick out a release before I start landing the new IR stuff on the main branch.
=> Bump version to public 2.3.3.

example/format.dart, lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/constants.dart, lib/src/dart_formatter.dart, lib/src/debug.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/import.dart, lib/src/piece/piece.dart, lib/src/piece/postfix.dart, lib/src/piece/sequence.dart, lib/src/testing/test_file.dart, pubspec.yaml, test/README.md, test/fix_test.dart, test/short_format_test.dart, test/tall_format_test.dart, test/top_level/export.unit, test/top_level/import.unit, test/top_level/library.unit, test/top_level/show_hide.unit, test/utils.dart
This gets the foundation in place for the new IR, the new visitor that produces it, the new line splitter that consumes it, the new style, and new tests for it. It also adds support for formatting library, import, and export directives to make sure everything is wired up together and working.
Existing formatting behavior is unchanged. You have to opt in to the new stuff by passing "tall-style" as an experiment flag.
This PR doesn't support comments, but it does leave some unused code in a few places that will be used to handle comments in future PRs. It has many UnimplementedError throws. Those will get filled in as more of the language is implemented in the new style. There are also two new kinds of TODO comments:
```
// TODO(tall): ...
```
These comments describe that work that needs to …
=> Start building the new Piece internal representation and new style.

lib/src/chunk_builder.dart, lib/src/comment_type.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/front_end/sequence_builder.dart, lib/src/piece/sequence.dart, lib/src/source_comment.dart, lib/src/source_visitor.dart, test/statement/block_comment.stmt
I'm working on getting argument lists formatting, including comments, and that pushed on a bunch of weak spots in the current way comments are handled. So I tried to clean that up first.
The general problem is comments are a sort of "fencepost" data structure where we need to track the number of newlines between each comment, including before the first and after the last. The previous code modeled that by having each comment store the number of lines before it, and then passing around a separate int for the number of newlines after it.
This commit adds a new CommentSequence class that models it directly and has nicer operations to get the newlines before or after any given comment. I believe it will make argument list comments easier to implement, and easier to share code with how …
=> Revamp how comments are handled.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/block.dart, lib/src/piece/import.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, lib/src/piece/postfix.dart, lib/src/piece/sequence.dart
Requiring the states to be a zero-based and contiguous makes it harder for some pieces to support different sets of different states based on what they contain. For example, an ImportPiece only supports states for splitting the names inside a single combinator when there is more than one combinator.
To model that with contiguous states requires the piece to carefully track how state indexes are shifted or splitting pieces into different classes to handle the different sets of states.
Instead, with this change, we simply allow the piece to return a list of states that may be non-contiguous. They can then omit states that don't make sense given the piece's contents. This makes ImportPiece simpler and I think will be useful for other pieces that have a variety of ways they can split.
Also …
=> Allow non-contiguous state values.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/assign.dart, test/expression/list.stmt, test/expression/map.stmt, test/expression/map_comment.stmt, test/expression/set.stmt, test/expression/set_comment.stmt, test/invocation/named_argument.stmt, test/statement/variable.stmt, test/statement/variable_comment.stmt
I'm formatting map entries the same way that assignments and variable declarations are handled, so that we get nice "block-like" formatting for delimited expressions, as in:
```
var map = {
list: [
1,
2,
]
};
```
While I was at it, I also updated named arguments to do the same thing:
```
function(
list: [
1,
2,
]
);
```
Also handle the "const" keyword on lists. I missed that when adding initial support for lists.
=> Format map and set literals.

lib/src/front_end/ast_node_visitor.dart, test/expression/other.stmt
Also use asserts() in some visit methods that we don't expect to be reachable because those AST nodes and handled at a higher level.
=> Format trivial expressions: null, doubles, this, symbols.

CHANGELOG.md, bin/format.dart, lib/src/source_visitor.dart, lib/src/testing/test_file.dart, test/utils.dart, test/whitespace/extension_types.unit
Attempt to format extension types. Since they are experimental, the syntax and formatting can still change before launch,
but this should make it *possible* to format code containing extension type declarations.
Which will make writing tests much nicer.
=> Add formatting for `extension type` declarations.

lib/src/back_end/code_writer.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/function.dart, lib/src/piece/list.dart, lib/src/string_compare.dart, test/expression/list_comment.stmt, test/invocation/comma_comment.stmt, test/statement/block_comment.stmt, test/statement/variable.stmt, test/string_compare_test.dart, test/type/function.stmt, test/type/function_comment.stmt
This involves formatting parameter lists which is a big piece of work. They work similar to argument lists and collection literals... except for the special syntax around `[ ... ]` and `{ ... }` for optional parameters.
Getting that working right involved adding some more functionality to DelimitedListBuilder and ListPiece.
Getting comments working with that syntax was particularly difficult. I ended up deciding that the formatter can move comments before or after the optional parameter delimiters if it needs to. Doing so produces better looking output, as in:
```
// Before:
f(// weird comment location
[param] // another
);
// After:
f([
// weird comment location
param, // another
]);
```
It also, I think is cleaner to implement than trying to laboriously keep the comment where the user …
=> Format function types.

lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/piece/assign.dart, lib/src/piece/block.dart, lib/src/piece/do_while.dart, lib/src/piece/function.dart, lib/src/piece/if.dart, lib/src/piece/import.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, lib/src/piece/postfix.dart, lib/src/piece/sequence.dart, lib/src/piece/variable.dart
The BlockPiece had some bespoke support for being in an "always split" configuration that overrode the two different ways it could be formatted. While working on conditional expressions, I found myself needing something similar to InfixPiece.
Instead of adding similar code to that and likely other pieces in the future, I figured it made more sense to bake support for locking a piece into a specific state directly in the Piece base class.
=> Support eagerly pinning a piece to a specific state.

lib/src/debug.dart
Prepare for lints 3.0.0 (PR #1289), which will report this as a dangling library comment, when it's probably just not intended a doc comment at all.
=> Turn top-library comment into non-dartdoc.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/sequence_builder.dart, lib/src/piece/list.dart, lib/src/piece/sequence.dart, test/expression/assignment.stmt, test/expression/switch.stmt, test/expression/switch_comment.stmt, test/statement/switch.stmt, test/statement/switch_comment.stmt, test/statement/variable.stmt
Switch statements build on the existing SequencePiece but need some additional flexibility in there to handle the fact that switch case lines are indented +2 and then case body lines are indented +4.
Switch expressions build on the existing ListPiece since the body is sort of like a collection literal. There are a few tweaks needed here too since an unsplit switch expression body gets spaces inside the curly brackets.
Also, switch values (the part in the leading "( ... )") are formatted using ListPiece as well, since they are formatted essentially like a single-element argument list, except that they don't get a trailing comma.
This does not implement all of the kinds of patterns that can appear in cases. It just implements basic constants needed for the tests. It also doesn't support …
=> Format switch statements and expressions.

lib/src/back_end/code_writer.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/list.dart
These classes started out just supporting argument lists, then grew to collection literals, then parameter lists, then switch expressions, and soon for loop headers.
Each time, I need to tweak how it works a little. (But not enough to not use it completely, since the comment handling is complex and is the same across all of those constructors.)
There was getting to be an unwieldy set of options being passed around. Cleaned that up by defining a separate ListStyle that contains those options and can be shuttled directly from DelimitedListBuilder to ListPiece.
I made the before and after bracket pieces optional since I'll be using ListPiece in a future PR for the updaters list in a for loop, which isn't delimited.
Did a bunch of other minor clean-up.
Also, many of the docs were out of date. …
=> Refactor ListPiece and DelimitedListBuilder.

example/format.dart, lib/src/testing/test_file.dart
The example script in example/format.dart has long been my sandbox script for debugging the formatter. One thing it has is a little helper function to run one of the format tests.
That helper code was copy/pasted from an ancient version of the test running code. Cleaned it up here to actually use the TestFile class now that there is some abstraction for running tests.
Also added support to example/format.dart to handle selections in tests.
(I'm starting to work on handling selections in the new formatter.)
=> Update test running code in example script.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/front_end/sequence_builder.dart
The current API is pretty confusing around when you should use `pop()`, `split()`, or both. If you get it wrong, sometimes it silently works but may leave a bug for later, or sometimes it fails it seemingly unrelated ways. Also, it's not clear whether you should call `pop()` first or `split()`. (It actually didn't matter.)
I tried to simplify the API some. It's still more subtle and brittle than I would like, but it's not clear to me if the complexity is essential. I'm trying to build Piece trees that don't have unnecessary nodes, so some slippage between AST node boundaries and Piece tree boundaries is essential.
I hope this API is better. The changes are:
- Make `split()` implicitly `pop()` the previous piece. This means you never need to call both `split()` and `pop()`. Just call …
=> Revamp the PieceWriter API some.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/list.dart, test/expression/record.stmt, test/expression/record_comment.stmt
Essentially the same piece logic used for other iterables.
- The `TypeLiteral` in `createCollection` has been broken down into its components for record literal re-use.
- Added a new `Comma` style which essentially describes that we need to preserve the comma after each element, regardless of splitting or not.
- Basic record tests.
=> Format record literals.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, lib/src/piece/function.dart, test/function/block_body.unit, test/function/default_value.unit, test/function/expression.stmt, test/function/expression_body.unit, test/function/generic.unit, test/function/local.stmt, test/function/other.unit, test/function/parameter.unit, test/tall_format_test.dart, test/variable/local.stmt
This covers:
- Top-level function declarations
- Local function declaration statements
- Anonymous function expressions
It handles all three kinds of bodies: `;`, `{ ... }`, and `=> ... ;`.
Most of the implementation work for functions is in:
- Their parameter lists, which is most already handled by the existing support (and tests) for function type annotations.
- Their `{ ... }` bodies, which are just block statements and are already implemented and tested.
- Their `=> ...` bodies, which are formatted like assignments so need little additional implementation.
This PR mostly just stitches that together, adds tests, and covers some of the bits that can't appear in those existing constructs:
- The `external` modifier on function declarations.
- Function names.
- Default values.
- The `var` …
=> Format function declarations and expressions.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/chain.dart, test/invocation/constructor.stmt, test/variable/local.stmt
Simple constructor calls behave exactly like normal function calls and use the same formatting code for their argument list.
Prefixed and/or named constructor calls are formatted sort of like method/property chains where they may split at the ".". We don't have full support for method/property chains yet, but this starts sketching that out enough to get the instance creation expression tests passing.
=> Format instance creation expressions (constructor calls).

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/function.dart, test/README.md, test/declaration/external.unit, test/declaration/field.unit, test/declaration/member.unit, test/declaration/method.unit, test/function/expression_body.unit, test/function/getter.unit, test/function/operator.unit, test/function/parameter.unit, test/function/setter.unit, test/type/function.stmt, test/variable/local.stmt, test/variable/top_level.unit
Almost all of the real work was already done to handle variables and functions, so this just extends that to fields and methods defined in classes and covers a few loose ends:
- External declarations in their various forms.
- The covariant modifier on parameters and fields.
- Operator declarations (which apparently were never tested on the old style!).
- Getters and setters.
- The `static`, `abstract`, and `late` modifiers.
I also tweaked the cost heuristics around splitting between return types, parameter lists, and `=>` expression bodies. It looks pretty weird to split after a return type, so I made that more costly than splitting at the body or parameter list. That in turn led me to tweaking the cost to split a type parameter list since those also look bad when split.
I also decided to …
=> Format fields and methods.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/declaration/mixin.unit, test/declaration/mixin_clause.unit
Almost nothing interesting here. The clauses are all handled the same way we handle clauses in a class declaration. We treat the `on` clause like the `extends` clause in a class, which means the other clauses can split while allowing the on clause to stay on the top line if it fits.
Mixin classes (and their various modifiers) were already handled because those are class declarations with a mixin modifier. Now there are tests for them.
=> Format mixin declarations.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, test/statement/for_in.stmt
I ended up refactoring the code for handling the for parts and inlining it all into visitForStatement() because it turns out that there isn't as much sharing between C-style for loops and for-in loops as I was expecting.
Thanks to the magic of pattern matching and shared case bodies, I was still able to get it all into a single flattened switch statement for all the kinds of for parts.
=> Format for-in loops.

lib/src/front_end/ast_node_visitor.dart, test/statement/other.stmt, test/statement/other_comment.stmt
Even smaller CL to handle await statements.
Await fors are handled in https://github.com/dart-lang/dart_style/pull/1314 which made this even simpler.
Also, there are no other existing tests for `await` because it's honestly too small of a piece. So no tests have been migrated.
I added one test to test the basic await + one for await with a comment.
=> Format await statements.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/sequence_builder.dart, lib/src/string_compare.dart, test/declaration/enum.unit, test/declaration/enum_comment.unit, test/declaration/enum_member.unit, test/declaration/enum_member_comment.unit, test/string_compare_test.dart
Format enum declarations with and without members.
Enums are a little tricky because they are sort of like lists (i.e. ListPiece) and sort of like type declarations (i.e. BlockPiece). Enums without members should be formatted pretty much like any other delimited list where the declaration can collapse to one line (and discard any trailing comma) if it fits or expand to one element per line (and add a trailing comma) otherwise.
Enums with members are formatted pretty much like blocks where each constant  or member is on its own line.
There are a few wrinkles around trailing commas and the semicolon between the constants and members:
-   If the enum has no members, any trailing `;` is discarded. It doesn't do anything useful and I consider this morally equivalent to discarding other …
=> Format enums

lib/src/front_end/ast_node_visitor.dart, test/statement/assert.stmt
This looks really similar to how asserts were formatted in the old formatter.
It's also similar logic to assert initializers, but we need constructors done first and then I'll handle that after.
I assume we have test logic for comments in ListPieces and general statements so I didn't add any extra for that, but if you think otherwise, let me know!
=> Format assert statements.

lib/src/back_end/solver.dart
Straight up dumb off-by-one error. 🙃 
This should make the solver a little faster (though it mostly uses the piece state map to look up states, so the shorter piece list won't have a huge effect).
The biggest practical effect is that the debug output of the solver is a lot easier to read because it isn't cluttered up by pointless pieces that it isn't solving for.
=> Ignore pieces with only one state during solving.

lib/src/debug.dart, lib/src/piece/adjacent.dart, lib/src/piece/assign.dart, lib/src/piece/block.dart, lib/src/piece/chain.dart, lib/src/piece/clause.dart, lib/src/piece/do_while.dart, lib/src/piece/for.dart, lib/src/piece/function.dart, lib/src/piece/if.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, lib/src/piece/postfix.dart, lib/src/piece/sequence.dart, lib/src/piece/type.dart, lib/src/piece/variable.dart
The old formatter has pretty nice debug output, but the new one is still pretty rudimentary. This improves that situation somewhat from:
```
Sequence(Type(`class Foo` Block(`{` Sequence(Var(`static late final int` `i;`) Var(`static late int` `i;`) Var(`static late var` `i;`) Var(`covariant late var` `i;`) Var(`covariant late int` `i;`) Var(`late final int` `i;`) Var(`late int` `i;`) Var(`late var` `i;`)) `}`)))
```
To:
```
Seq(
Type(
`class Foo`
Block(
`{`
Seq(
Var(`static late final int` `i;`)
Var(`static late int` `i;`)
Var(`static late var` `i;`)
Var(`covariant late var` `i;`)
Var(`covariant late int` `i;`)
Var(`late final int` `i;`)
Var(`late int` `i;`)
Var(`late var` `i;`)
)
`}`
)
)
)
```
It also eliminates a bunch of pointless `toString()` implementations that are only used for …
=> Better debug output for piece trees.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, lib/src/piece/list.dart, lib/src/source_visitor.dart, test/expression/switch.stmt, test/invocation/block_argument_comment.stmt, test/invocation/block_argument_kind.stmt, test/invocation/block_argument_multiple.stmt, test/invocation/block_argument_other.stmt, test/invocation/constructor.stmt, test/invocation/function.stmt, test/statement/assert.stmt, test/statement/switch.stmt, test/variable/local.stmt
Sometimes in an argument list, we don't want to force it to full split even if an argument contains an inner newline. In other words, we want to prefer:
```
test('hi', () {
body;
});
```
Over:
```
test(
'hi',
() {
body;
},
);
```
The latter is what you would normally get when an argument contains a newline. This change enables the former. The heuristics for what kinds of arguments are allowed to have this block-like formatting, how many of them, and what other arguments are allowed are pretty fuzzy.
I picked a simple set of rules here (which follow the prototype), but left some TODOs because I suspect we will iterate on them later once we can run the new formatter on larger codebases.
The heuristic for what kinds of arguments are block-like is the same rule that we use for "delimited" …
=> Support "block argument" formatting.

lib/src/back_end/code_writer.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/piece.dart
The formatter currently mostly relies on the surrounding piece's setAllowedWhitespace() rules to make sure that a line comment forces the surrounding piece to split in a way that ensures there is a newline after the comment.
This works correctly in lots of places where line comments are actually expected, but isn't reliable when a line comment occurs in a weird location. When that happens, it's important that we still always put a newline after the comment. Otherwise the code is meaningfully changed.
This does that. Whenever a TextPiece ends in a line comment, it will know that it has a trailing newline. It then always writes that to the CodeWriter. That leads to redundant newlines in cases where the surrounding piece is already going to put a newline, so I also moved some of the …
=> Ensure that line comments always get newlines after them.

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml
This commit has already been rolled into the SDK and internally, so getting ready to publish a new version of the dart_style package.
cc @kallentu @natebosch
=> Bump version to publish 2.3.4.

CHANGELOG.md, lib/src/dart_formatter.dart, pubspec.yaml
Since extension types are now enabled by default (https://github.com/dart-lang/sdk/commit/a19ae4ee688e5297ef95970eb1077cba3fddb5eb) and `dart_style` supports formatting extension types, the language version passed to the analyzer should be updated.
Reference: https://github.com/dart-lang/sdk/issues/54139#issuecomment-1824826027
=> Parse with language version 3.3

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/adjacent.dart, lib/src/piece/try.dart, test/statement/try.stmt, test/statement/try_comment.stmt
- Added a new `TryPiece` for try statements. They are very similar to if statements, but I kept them separate.
- Each `TryPiece` has one or more `_TrySectionPiece` which is a catch or finally header and block. They're all formatted similarly.
- Tests for trys and their comments.
Will also remove the temp dir tests after submission.
(I'll send this over to Nate for readability after approval :D )
=> Format try statements.

lib/src/back_end/code_writer.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, lib/src/piece/constructor.dart, lib/src/piece/function.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, test/declaration/constructor.unit, test/declaration/constructor_assert.unit, test/declaration/constructor_comment.unit, test/declaration/constructor_initializer.unit, test/declaration/constructor_parameter.unit, test/declaration/external.unit
Includes everything that can go in a constructor:
- Factory and redirecting constructors.
- Initializing formals ("this." parameters).
- Super parameters.
- Constructor initializers.
- Assert initializers.
Constructors are tricky because there are some constraints between how the parameter list and initializer list are allowed to split. Up until now, aside from setAllowNewlines(), there aren't really any ways that pieces interact.
To support this, I added a pretty simple API where when a piece calls CodeWriter.format() on a child piece, it can pass it what state the piece is required to be in. If the solution doesn't have the child in that state, it invalidates the solution.
It seems to work pretty well. There is probably a more optimal way to implement that in the solver so that we test …
=> Format constructor declarations.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/piece/constructor.dart, lib/src/piece/piece.dart
When I added support for constructors, I introduced a little API to let pieces enforce constraints between their state and the states of other child pieces. It worked but felt a little bolted on. In particular, enforcing the constraints during CodeWriter formatting meant we didn't prune invalid solutions as efficiently as we could.
I'm working on if elements now and I needed a better way to handle constraints between pieces for that, so I went ahead and refactored the way this works to be, I think, generally better:
- Enforce constraints between pieces during solution expansion instead of during formatting. This means that we eagerly discard any solution (and the whole tree of solutions that could have come from it) if it doesn't meet the constraints.
- Remove the `_pieces` fields in …
=> Refactor how piece constraints are applied.

lib/src/front_end/ast_node_visitor.dart, test/type/function.stmt
Small PR to format function references -- really just builds upon type argument formatting.
I also migrated previous function reference tests over.
=> Format function references.

lib/src/ast_extensions.dart, lib/src/comment_type.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/assign.dart, lib/src/piece/chain.dart, lib/src/piece/clause.dart, lib/src/piece/constructor.dart, lib/src/piece/for.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/postfix.dart, lib/src/piece/variable.dart
Not exactly the most impactful change. :) But in a previous PR, Nate suggested that old-style Markdown indentation for code blocks would be better than backticks since it's shorter and we aren't actually running the comments through a Markdown formatter anyway.
This converts all of them over in on Go so the codebase is consistent.
=> Change code blocks to use indentation instead of backticks.

lib/src/front_end/ast_node_visitor.dart, test/expression/postfix.stmt
This also includes temporary formatting support for a few syntactic forms that the postfix tests needed to use. I left TODOs in there so that we know that support for those isn't complete yet.
=> Format postfix expressions: `!`, `++`, and `--`.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, test/expression/collection_for.stmt, test/expression/collection_for_comment.stmt, test/expression/collection_for_in.stmt, test/expression/collection_for_spread_list.stmt, test/expression/collection_for_spread_map.stmt, test/expression/collection_for_spread_set.stmt, test/statement/for_in.stmt
This mostly uses the existing code for formatting the `for (...)` part of for statements, which I moved into PieceFactory so that it can be reused.
In the process of adding tests for this, I noticed that a newline in the initializer of a for-in loop forced the `in` to split, which looks weird, so I fixed that too, for both for statements and for elements.
I also added trivial support for postfix expressions because some of the for element tests use `i++`. I didn't migrate the tests for those yet since they aren't really related to this change, so added a TODO to do that in a later PR.
=> Format for elements.

lib/src/front_end/piece_factory.dart
In the old and new style, if a newline occurs in the pattern of an if-case statement or element, it forces a split before the `case` too. That syntax is structurally similar to for-in loops, but for-in loops currently don't force that split. (And I had to add explicit support to *not* force a split there.)
Update the TODO comment to consider whether we want to make for-in loops format similar to if-case.
=> Update TODO comment on for-in to consider how "in" should split.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/chain_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/chain.dart, test/expression/postfix.stmt, test/invocation/chain.stmt, test/invocation/chain_block.stmt, test/invocation/chain_comment.stmt, test/invocation/chain_postfix.stmt, test/invocation/chain_property.stmt, test/invocation/chain_target.stmt, test/invocation/constructor.stmt, test/invocation/null_aware.stmt
This handles unsplit call chains, fully split ones, as well as block-style calls, like:
```
target.call(
argument,
);
```
This doesn't fully implement the proposal I sketched out because it only allows a single block call. There's a long TODO(tall) comment about whether we want to do that, but I figured it makes sense to do that as a separate iteration since there is so much in here.
But it implements most of it, and I've migrated all of the existing tests over. It ended up being both simpler than the old formatter while also producing better output.
The old formatter has a restriction where the indentation of a piece of code must be fixed regardless of which way it splits. It can't handle:
```
// Block style, so indent argument +2:
target.property.call(
argument
);
// Can't do block …
```
=> Format call chains!

lib/src/front_end/ast_node_visitor.dart, lib/src/source_visitor.dart, test/declaration/class.unit, test/utils.dart, test/whitespace/classes.unit
In order to use this, you have to pass "--enable-experiment=macros" to the formatter (which the formatter tests now pass).
This adds support to both the old and new styles.
=> Format the experimental "macro" keyword before classes.

lib/src/front_end/ast_node_visitor.dart, test/statement/if_case.stmt, test/statement/if_case_comment.stmt
This is previous behaviour from the old formatter that would prefer splitting at the `case` keyword.
We want to retain this behaviour and I added a few tests for this.
We also need this because it seems to be used by most pattern tests.
=> Prefer splitting before case in an if-case.

lib/src/back_end/code_writer.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/piece/assign.dart, lib/src/piece/variable.dart, test/README.md, test/pattern/declared_variable.stmt, test/pattern/declared_variable_comment.stmt, test/statement/if_case_comment.stmt, test/tall_format_test.dart
- Added a `pattern` test directory.
- Implemented `visitDeclaredVariablePattern`'s splitting using an `AssignPiece`.
- Added `_indentInValue` to `AssignPiece` which adds extra indentation to the `value` when split and should be used for all patterns that have the similar splitting and indenting as declared variable patterns.
Indentation for some of the comment cases are a little weird, like this one:
```dart
if (obj
case true // comment
) {
;
}
```
But this is probably fine for how much this occurs.
=> Format declared variable pattern.

lib/src/ast_extensions.dart, lib/src/back_end/code_writer.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/piece.dart, test/expression/interpolation.stmt, test/expression/string.stmt, test/expression/string_comment.stmt, test/invocation/block_argument_multiple.stmt, test/invocation/block_argument_string.stmt, test/selection/selection.stmt, test/tall_format_test.dart
In the old style, the formatter has some special code to discard line splits that occur inside string interpolation expressions. That's largely for historical reasons because the formatter initially didn't support formatting of string interpolation expressions *at all* and I didn't want too much churn when adding support for formatting them.
In the new style here, we don't do that: The contents of a string interpolation expression are split like any other expression. In practice, it doesn't matter much since users generally reorganize their code to avoid long strings and splits in string interpolation. This way leads to less special case code in the formatter.
This change is somewhat large because I also reorganized how newlines inside lexemes are handled in general. Previously, TextPiece …
=> Format multi-line strings and string interpolation.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, test/pattern/list.stmt
Changes
- Add an extension to `DartPattern` so we can block split `ListPattern`s.
- Implemented `visitListPattern` and `visitRestPattern`.
- Avoid extra indentation in `AssignPiece` when we are (inner) block splitting.
- Migrated existing list pattern tests.
=> Format list pattern and rest pattern.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/piece/adjacent_strings.dart, lib/src/piece/list.dart, test/expression/string_adjacent.stmt, test/expression/string_adjacent_comment.stmt, test/invocation/block_argument_multiple.stmt
Most of this was fairly straightforward, but the two tricky bits are:
There are some rules around whether subsequent strings in the adjacent strings get indented or not. The answer is yes in some cases to avoid confusion:
```
var list = function(
'string 1',
'adjacent'
'string 2',
'string 3',
];
```
But not in others since it looks nicer to line them up when possible:
```
var description =
'some text '
'more text';
```
It's really important that test functions don't end up fully split because doing so would lead to the inner function expression getting indented +2:
```
test('this looks good', () {
body;
});
test(
'this looks bad',
() {
body;
},
);
```
Test descriptions often span multiple lines using adjacent strings:
```
test('this is a very long test description '
'spanning multiple …
```
=> Format adjacent strings.

lib/src/front_end/ast_node_visitor.dart, test/invocation/super.stmt
Apparently the old formatter has *zero* tests of this. I went ahead and wrote tests of all of the ways `super` appears in the grammar. That's probably overkill given that the analyzer models `super` as a standalone expression, but that's not actually how it works in the language itself. (In Dart, `print(super)` isn't syntactically valid.)
I figured it made sense to write tests closer to the grammar.
=> Format super expressions.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/chain_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/chain.dart, test/invocation/block_argument_kind.stmt, test/invocation/cascade.stmt, test/invocation/cascade_comment.stmt, test/invocation/cascade_mixed.stmt
There were a couple of tricky corners, but this wasn't as bad as I'd feared. Most of ChainBuilder worked great for it.
In the process of doing this and migrating the tests, I noticed another kind of expression that should allow block formatting in an argument list: function expression invocations.
That's a `(...)` where the thing on the left is some kind of expression and not simply a name, like: `(foo + bar)(args)`.
Added support for that and added some tests of block formatting for those too.
I believe this is the last corner of the grammar where there might be some weird tricky formatting logic to implement. There's a lot still left to cover, but I think it's all syntactically similar to other already-implemented constructs. I'm breathing a  big sigh of relief because I think this …
=> Format cascades.

lib/src/back_end/code_writer.dart, test/invocation/chain_postfix.stmt
The Solver selects states for all pieces in the piece tree to decide how to format. It does so by exploring a tree of incremental solutions where each set of states is a node in the tree and branches are formed by incrementally binding new states.
Exploring the full tree is massively slow. A key optimization is that the solver only looks at changing the state of pieces on lines that actually overflow or are invalid. That way pieces on lines that fit and don't need to split are ignored.
It goes further: it only looks at the *first* piece on the *first* line that overflows. Any pieces following that one may be affected by how changing the state of the preceding piece changes the formatting, so we ignore those.
At least, that's the intent. It turns out there's actually a bug and the solver …
=> Fix bug where solver looks at the last piece on line instead of first.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/pattern/map.stmt, test/pattern/map_comment.stmt
- Map patterns and entries are now formatted.
- Migrated map pattern tests.
- Altered `createAssignment` so it can take `AstNode`s and calculate `allowInnerSplit` depending on which node.
=> Format map patterns.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart
Prune solutions derived from invalid ones.
A solution is invalid if a child piece writes a newline at a point in time where a parent disallows newlines.
When that happens, the parent's may be explicitly bound to a state by the solution, or it may still be in an unbound state (and thus using the default). If unbound, then even though this solution is invalid, it may lead to later valid ones by binding that parent piece to a different state.
But once a solution binds a piece to a state, all solutions derived from that state keep the same binding. So if we hit an invalid solution and the piece whose newline constraint was already violated, we can discard that solution and all possible solutions derived from it.
This skips an entire potentially huge subtree from the solution space being …
=> Prune solutions derived from invalid ones.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/pattern/record.stmt, test/pattern/record_comment.stmt
- Added the helper `createRecordCollection` to handle similar trailing comma situations for record types and patterns.
Records should only have an always trailing comma with a single positional field, in every other scenario, it will have a regular trailing comma style (if split).
- Migrated record pattern tests from the temp repo.
- Allow `RecordPattern` to block split.
=> Format record pattern.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/piece/if.dart, lib/src/piece/piece.dart
In the process of turning ListElement into a Piece, I ran into a couple of bugs in how pinned states and constraints between pieces are handled.
The tests didn't catch those bugs because there are basically two bugs that cancel out. The IfPiece was incorrectly pinning an empty else block in an if statement to split. But the solver was incorrectly ignoring pinned states in some cases. This fixes both bugs.
With this change, when generating a Solution, we eagerly bind as many Pieces to States as we can when the Solution is first created before running CodeWriter. To do that, we find all of the pinned Pieces and bind them to their pinned States, then propagate any constraints from that to other child Pieces.
This fixes a couple of bugs, but also, I think, leads to a cleaner module where at …
=> Reorganize how Solution handles pinned states and constraints.

lib/src/back_end/solution.dart, lib/src/piece/sequence.dart, test/regression_tall/other/misc.unit, test/tall_format_test.dart
An important optimization during solving is hoisting out a separable Piece subtree, formatting in its own isolated Solver, and then merging the resulting Solution back into the parent Solution.
When we merge, we add in all of the data from the subtree to the main one. It's important that doing so yields the exact same result that we would get if we had solved that subtree directly inline in the parent Solution.
Unfortunately, the previous code didn't do that. In some cases, pieces that are bound by the subtree Solution would already be bound in the parent one too. In that case, merging would double-count the cost of those pieces.
This fixes that by only counting the cost of pieces that weren't already bound in the parent.
I ran into this bug while running the large benchmark and it was …
=> Fix bug in subtree merging cost calculation.

lib/src/back_end/solver.dart, test/pattern/declared_variable_comment.stmt
While the Solver is working through Solutions, it keeps track of the best Solution it's found so far. This will get returned if there is no Solution that fits within the page width: when overflow is inevitable, the formatter still tries to do the best it can.
The Solver is careful to not consider an invalid solution (one that contains a newline where none is allowed) to be the best solution. Except in one case: If the *initial* solution is invalid, the Solver will still store it in best. Then, as long as no other solution has less overflow than the initial invalid one, it ends up returning an invalid solution.
This fixes that: any valid solution, regardless of overflow, will kick out that initial invalid solution if there is one.
=> Prefer any valid solution over an invalid one, regardless of overflow.

lib/src/back_end/code_writer.dart, lib/src/back_end/solver.dart, lib/src/constants.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/piece/adjacent_strings.dart, lib/src/piece/assign.dart, lib/src/piece/chain.dart, lib/src/piece/clause.dart, lib/src/piece/constructor.dart, lib/src/piece/for.dart, lib/src/piece/function.dart, lib/src/piece/if.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/postfix.dart, lib/src/piece/sequence.dart, lib/src/piece/variable.dart, test/pattern/constant.stmt, test/pattern/declared_variable_comment.stmt, test/pattern/list.stmt, test/pattern/logic.stmt, test/pattern/map.stmt
Trying to get infix patterns indenting correctly has proved surprisingly hard. This PR does it, but it does so by first doing some significant refactoring to CodeWriter, and then adding a new indentation mechanism that is only used by if-case. I'm not sure if it's the best approach.
The way if-case statements are styled in the new back end is a little unusual. Here are some examples:
```dart
if (object
case first ||
second ||
third ||
fourth) {
;
}
if (object
case veryLongPrefix
.longIdentifierName) {
;
}
if (obj
case SomeLongTypeName
longVariableName) {
;
}
if (obj
case var // c
x) {
;
}
```
In all four examples, the line after the `case` line is indented +4 relative to the previous line. The tricky part is: *Where* does that indentation come from?
Infix operators indent their subsequent …
=> Format logic and parenthesized patterns

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/case.dart, lib/src/piece/infix.dart, test/expression/switch.stmt, test/expression/switch_comment.stmt, test/expression/switch_guard.stmt, test/statement/switch.stmt, test/statement/switch_guard.stmt
There were enough tweaks in the formatting specific to the two contexts where the guards can appear that I ultimately decided to make new Piece classes for switch expression cases and switch statement cases. I was hoping for more code reuse, but I think it would have been harder to maintain if I jammed all of this into a single Piece class.
I also slightly tweaked the indentation style of switch expression cases. When I'd first added support for switch expressions in the new formatter, I changed the style from what the old formatter had, for reasons that aren't entirely clear. Maybe I thought it made it more consistent to indent +4?
Either way, once guard clauses came into play, it became clear that the old style made more sense because it gives a clearer indentation level for the `when` …
=> Format guard clauses in switches.

test/pattern/constant.stmt
Tried to do some check of what patterns we have left using the tests, and realized these aren't migrated (I think).
The list/map/record tests aren't the actual `ListPattern`, `MapPattern` etc, so labelled this more as an overall `constant.stmt`.
=> Migrate constant pattern tests to tall formatter.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, test/pattern/object.stmt, test/pattern/object_comment.stmt
- Added `ObjectPattern`s to `canBlockSplit`.
- Migrated object pattern tests and object patterns with comments tests.
There's one test case in there that's not great, but I think it's a general problem with `ListPattern`, `MapPattern` too. 
Maybe revisit it with the other patterns in another CL.
```
>>> Split in type argument.
if (obj case LongClassName<First, Second>()) {;}
<<<
if (obj
case LongClassName<
First,
Second
>()) {
;
}
```
=> Format object patterns.

lib/src/front_end/adjacent_builder.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/sequence_builder.dart, lib/src/piece/list.dart, lib/src/piece/sequence.dart, test/README.md, test/declaration/enum_metadata.unit, test/declaration/member_metadata.unit, test/declaration/metadata.unit, test/declaration/metadata_comment.unit, test/function/metadata.unit, test/top_level/metadata.unit, test/type/metadata.stmt, test/variable/metadata.unit
This handles metadata everywhere except on for loop variables. I'll do that later after patterns in for loops are supported.
Since there were some metadata tests on pattern variable declarations, this also includes a trivial implementation of that. There's a TODO to revisit it and add real tests, but it's enough for the metadata tests.
Figuring out where to put the metadata-handling code was a little tricky since so many places in the language can have metadata. I ultimately decided to put it into AdjacentBuilder. Every place that was working with metadata also had one of those builders in play, so that made it easy to add a simple call to `b.metadata()` and get the metadata working.
It does mean that AdjacentBuilder isn't strictly about adjacent pieces anymore, but I think that's OK. In …
=> Format metadata annotations.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, test/expression/collection_for.stmt, test/statement/for.stmt, test/statement/for_in.stmt, test/variable/pattern.stmt
This required pretty significantly revamping AssignPiece since now there can be complex syntax on the left side of the `=` too. It went through several iterations but I think I managed to simplify it down to something reasonable that still passes all of the tests.
This PR doesn't do pattern assignment, but that should hopefully be a trivial change after this.
=> Format pattern variable declarations, including in for loops.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/pattern/other.stmt, test/pattern/other_comment.stmt, test/pattern/relational.stmt, test/pattern/relational_comment.stmt
Since `!` and `?` are structurally identical, I added a createPostfix() helper to PieceFactory for them. Then I went ahead and also refactored the existing postfix-like forms to use that.
Likewise with relational operators and createPrefix().
These are the last UnimplementedErrors in the new back end!
=> Format relational, null-check, and null-assert patterns.

test/declaration/class_comment.unit, test/function/comment.unit
The old formatter style had a special rule that any line comment that was already at column 1 (i.e. the left edge) would not be indented, even if the surrounding code would otherwise indent it. So if you wrote:
```dart
class C {
void foo() {
// comment
}
}
```
Then the formatter would output:
```dart
class C {
void foo() {
// comment
}
}
```
And not:
```dart
class C {
void foo() {
// comment
}
}
```
The intent was that if you commented out a block of code in your editor, like:
```dart
class C {
void unused() {
//    code();
}
}
```
Then the formatter wouldn't then add *more* indentation:
```dart
class C {
void unused() {
//    code();
}
}
```
But in the editors I've tested (VS Code, IntelliJ, Sublime Text, emacs), when they comment out code, they all put the line comment markers *after* …
=> Test that the new style doesn't keep line comments flush left.

lib/src/front_end/comment_writer.dart
The TODO questions whether we should make a distinction between C-style block comments that have newlines around them in the original source or not. If we don't, then the formatter would turn code like:
```dart
main() {
/*
entireBody();
commentedOut();
forSomeReason();
*/
}
```
Into:
```dart
main() {/*
entireBody();
commentedOut();
forSomeReason();
*/}
```
I did a little scraping of a corpus, and there are quite a few block comments like this in the wild, and I think it looks better to keep them on their own lines if the input code has a newline before or after the comment.
Also, the implementation complexity of distinguishing inline block comments and non-inline ones is trivial. Removing support for it would change like three lines of code.
So I think it's best to just keep supporting …
=> Remove TODO about non-inline block comments.

lib/src/front_end/ast_node_visitor.dart
It turns out the trivial implementation is sufficient, and I migrated tests over in a previous PR.
=> Remove TODO that's already TODONE.

lib/src/back_end/code_writer.dart, test/pattern/object.stmt
I'm honestly not sure what the TODO was even trying to say. But I think the formatter behaves like we want here so there's nothing TODO as far as I can tell. But this corner did seem a little under tested, so added some more.
=> Add more tests for type arguments in object patterns and remove a TODO.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, lib/src/piece/for.dart, lib/src/piece/if.dart, test/expression/collection_for_in.stmt, test/expression/collection_for_metadata.stmt, test/function/expression_body.unit, test/function/generic.unit, test/function/operator.unit, test/pattern/object.stmt, test/statement/for_declaration.stmt, test/statement/for_in.stmt, test/statement/for_metadata.stmt, test/variable/pattern.stmt
When I added support for metadata, I skipped metadata on for loop variables because I thought it would be a little annoying and wanted to do it separately. Boy was I right.
Jamming metadata in there highlighted a handful of other formatting bugs in for loops, which in turn made some general bugs in how block-like constructs to the left of assignments (which includes `=`, `=>`, and `in`) are handled. There were a lot of tests, but there are just so many combinations of kinds of syntax on the left of an assignment-like thing and expressions on the right that's hard to cover everything.
So I revamped that first. Then I added support for for loop metadata.
To make it easier to review, I tried to break it into bite-sized meaningful commits.
=> For loop metadata

lib/src/back_end/solution.dart, lib/src/piece/piece.dart
Before this change, constructor for Solution would recursively traverse the entire piece tree from the root down. It did so looking for pieces that were pinned, so that it could add them to the pieceState map and (more importantly) apply any constraints that the pinned piece's state implies on other child pieces.
Unfortunately, this traversal interacts poorly with the optimization to format some piece subtrees separately. The Solution constructor for the root piece would traverse the whole tree, then Solution constructors for any child pieces being formatted separately would also traverse their piece trees, and so on.
In practice, it was roughly quadratic. Oops. :(
This change removes that traversal completely. Instead, when a piece is pinned, we apply any constraints at that point in …
=> Don't eagerly bind pinned Pieces in Solution.

benchmark/case/flutter_scrollbar_test.expect, benchmark/case/flutter_scrollbar_test.expect_short, benchmark/case/flutter_scrollbar_test.unit, benchmark/case/large.expect, lib/src/ast_extensions.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/piece/list.dart, lib/src/piece/sequence.dart, test/invocation/block_argument_kind.stmt, test/invocation/block_argument_multiple.stmt, test/invocation/block_argument_other.stmt, test/statement/assert.stmt
I was trying out the new formatting on Flutter and noticed a few issues:
**1. Immediately-invoked functions in asserts are common.**
Prior to this change, these were not block format candidates, giving you:
```dart
assert(
() {
// Some slow computation...
}(),
'Message.',
);
```
With this change, they're treated like (uninvoked) function expressions:
```dart
assert(() {
// Some slow computation...
}(), 'Message.');
```
**2. Formatting large deep widget trees looks weird.**
Prior to this change, a function call inside an argument list can be treated like a block argument even if there are other arguments. That tends to pack things in strangely in widget code, like:
```dart
SizedBox(height: 1000.0, width: double.infinity, child: Column(
children: <Widget>[Scrollbar(key: key1, child: …
```
=> Tweak the heuristics on which expressions allow block formatting.

CHANGELOG.md, lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solution_cache.dart, lib/src/back_end/solver.dart, pubspec.yaml
I was working on an unrelated bug fix and I stumbled into a couple of incorrect formats in some complex examples. After poking around, I found two bugs:
- In SolutionCache, it always used the given state of the root Piece even if that state wasn't explicitly bound in the parent Solution. This causes incorrect output if we are separately formatting a child, the parent Solution doesn't bind the child's root, and the best state for the child is *not* the unsplit state.
That's a rare enough combination of events that none of the existing tests hit it, but I'll have some new tests for the unrelated bug fix that do.
- In Solution, when applying constraints between pieces, it doesn't take into account conflicts from pinned pieces. This bug was introduced by #1407. It wasn't caught because the …
=> Fix two bugs around pinned states in the Solver and SolutionCache.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solution_cache.dart, lib/src/back_end/solver.dart, lib/src/front_end/chain_builder.dart, test/invocation/cascade.stmt, test/regression_tall/other/flutter.unit
I did a test run of the new formatter on the Flutter repo and it hit some crashes in cascades where a cascade section contains a method chain like `foo..a.b`.
While investigating that, I realized that the existing code for formatting cascades tries to reuse the regular method chain formatting code entirely unnecessarily.
This fixes the crash, and the formatting, and is simpler for handling cascades.
=> Fix a crash and some formatting bugs in cascades.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, test/declaration/constructor_assert.unit, test/expression/collection_if.stmt, test/expression/collection_spread.stmt, test/expression/list.stmt, test/expression/map.stmt, test/expression/map_comment.stmt, test/expression/record.stmt, test/expression/set.stmt, test/invocation/chain.stmt, test/pattern/cast.stmt, test/statement/switch_legacy.stmt, test/top_level/trailing_whitespace.unit, test/top_level/unicode.unit, test/variable/pattern.stmt
In the process, I discovered a bug where the formatter would allow any list-like construct (collection literal, etc.) to support block formatting, which is definitely not intended. Only argument lists should allow that.
Fixed that bug.
=> Migrate more tests over to the new style.

CHANGELOG.md, lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/source_visitor.dart, pubspec.yaml
I introduced a hack to fix #1413. This bumps the analyzer constraint and removes that hack.
=> Require analyzer 6.3.0 and remove corresponding hack.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/expression/collection_for.stmt, test/expression/collection_for_spread_list.stmt, test/expression/collection_for_spread_map.stmt, test/expression/collection_for_spread_set.stmt, test/expression/collection_if.stmt, test/expression/collection_if_spread_list.stmt, test/expression/collection_if_spread_map.stmt, test/expression/collection_if_spread_set.stmt, test/expression/list_nested.stmt, test/expression/map_nested.stmt, test/expression/record_nested.stmt, test/expression/set_nested.stmt, test/pattern/list.stmt, test/pattern/map.stmt, test/pattern/record.stmt
If a list, set, or map literal contains (directly or indirectly) another list, set, or map literal, then force the outer one to split, even if it would otherwise fit.
We don't do this for record expressions, or any kind of pattern because those tend to be smaller and look better when kept closely packed.
The behavior here is exactly the same as in the current formatter.
=> Force list, set, and maps to split if they are nested.

lib/src/front_end/piece_writer.dart
The formatter library API allows you to pass in a number of leading indent spaces that will be applied to all lines of the output. This is used internally for the regression tests (which often need to preserve the indentation of the surrounding context of the original failing code). It's also supported by the API so that some editors which support "format just this selection" can pass in a leading indent of the surrounding context.
This passes that through to the new formatter.
(It wasn't caught by tests because the API and command-line tests are currently not forked to run the new style too.)
=> Support leading indentation in the new style.

lib/src/ast_extensions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/piece_factory.dart, lib/src/source_visitor.dart, test/expression/list_preserve_newlines.stmt, test/expression/map_preserve_newlines.stmt, test/expression/record_preserve_newlines.stmt, test/expression/set_preserve_newlines.stmt, test/invocation/block_argument_comment.stmt, test/invocation/comment.stmt
Large collection literals often have some internal structure that the author wants to highlight by having multiple elements on one line, sort of like a matrix.
The old style has a sort of hacky but in practice useful heuristic to enable that: if a collection literal contains a line comment, then the newlines (or lack of) between pairs of elements are preserved:
https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals
This implements that same heuristic in the new style. The behavior is slightly different in the new style. In the old style, an argument list can be split in a variety of ways:
```dart
// 1. All on one line:
f(argument1, argument2, argument3, argument4)
// 2. Split into two lines at after any particular argument:
f(argument1, …
```
=> Preserve newlines (or lack of) in collections with line comments.

lib/src/ast_extensions.dart, test/invocation/block_argument_kind.stmt, test/variable/local.stmt
When I first added support for block formatting arguments in the new style, I allowed function expressions with `=>` bodies if they had parameters with the idea that the parameter list itself would get the block-like formatting, as in:
```dart
function((
parameter1,
parameter2,
) => body);
```
I'm honestly not sure why I thought that was a good idea. The old formatter doesn't allow that. I don't think it looks particularly good. And, worst of all, the formatter doesn't actually *require* the parameter list to be the place where the split occurs, so the current implementation allows unwanted output like:
```dart
function((parameter) => operand +
anotherOperand));
```
This is definitely not intended.
I've started migrating regressions tests and in the examples I've seen where this rule …
=> Tweak the block formatting rules to disallow `=>` function expressions.

lib/src/front_end/chain_builder.dart, lib/src/piece/chain.dart, test/tall/invocation/cascade.stmt
I'm working on migrating the regression tests and tweaking the new formatting heuristics as I go based on the results I see in those real-world examples.
In a method chain, if the target can be block formatted, we prefer to split in the target and not at the ".". So:
// Prefer:
[
target,
block,
].doStuff();
// Over:
[target, block]
.doStuff();
Prior to this PR, it had the same priority for single-section cascades:
// Prefer:
[
target,
block,
]..doStuff();
// Over:
[target, block]
..doStuff();
But for cascades, I think the cascade operation is "looser" and generally looks better to put it on its own line and leave the target unsplit when possible. So this change flips priority and prefers:
[target, block]
..doStuff();
In larger more realistic examples, I think it looks better. In general, …
=> Prefer splitting at ".." instead of in the cascade target.

lib/src/front_end/sequence_builder.dart, test/tall/expression/switch_comment.stmt, test/tall/statement/switch_comment.stmt
Before this fix, line comments inside a switch case body would be indented to align with the case, not the body. This aligns them with the case body, except for comments inside a case but after the body. Those are still aligned to the case level because most of the time when comments appear at the end of a case body, they describe the subsequent case, like:
```dart
switch (obj) {
case 1:
body;
// Comment here describes next case:
case 2:
body;
}
```
=> Indent comments inside switch statement cases.

lib/src/front_end/adjacent_builder.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/chain_builder.dart, lib/src/front_end/piece_factory.dart, test/tall/invocation/cascade.stmt
Convert every place where a parent AST node affects how the child node is formatted to use NodeContext instead of calling `.parent` on the AST node.
This addresses the discussion https://github.com/dart-lang/dart_style/pull/1431#discussion_r1540225326 at least for the cases where context flows from parent to child (i.e. the `.parent` calls).
There are still a number of places where context flows from child to parent: splitting collections that contain collections, block arguments, and block calls in chains. Each of those has different enough needs that I think the current solutions for each one are fine.
=> Use NodeContext for all downwards contextual formatting.

test/tall/regression/other/tall_prototype.unit
When I was working on the prototype implementation, I ran it on a bunch of codebases. I got it working as well as I could but I sometimes noted cases where the prototype did the wrong thing. I held onto them to make sure that the real implementation is better.
These are most of those cases. I still have a few where the new formatter needs a tweak or two to get it right, but these ones are already doing the right thing.
=> Add some regression tests from the old prototype.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/list.dart, lib/src/piece/type.dart, test/tall/declaration/enum_clause.unit
There was an old test for this but somehow I must have dropped the clause parts of that test when migrating it and then forgot to implement clauses on enums.
Handling this required juggling some code around because, unlike most other type declarations, we allow the body of an enum to not split if it only contains values and no members. But we also want to force the enum values to split if there is a split in the header. (This is almost never relevant because if you have a `with` or `implements` clause in an enum, you almost certainly want to define some members too, but the formatter should do the right thing regardless.)
In the process of working on this, I noticed that
ListStyle.splitListIfBeforeSplits is no longer used, so I removed that.
=> Format `with` and `implements` in enum declarations.

benchmark/case/flutter_popup_menu_test.expect, benchmark/case/flutter_popup_menu_test.expect_short, benchmark/case/flutter_popup_menu_test.unit, benchmark/case/flutter_scrollbar_test.expect, benchmark/case/large.expect, lib/src/front_end/delimited_list_builder.dart, test/tall/invocation/block_argument_kind.stmt, test/tall/invocation/other.stmt, test/tall/statement/assert.stmt
I've been running the new formatter on the Flutter repo looking for ugly output and performance problems. (Mostly the latter.) One source of pathologically bad performance is nested function call block arguments. It's not a problem with block arguments in general because when a collection is a block argument, the collection itself doesn't support block arguments. But consider:
```
f1(f2(f3(f4(f5(f6(f7(f8(f9(f10(arg))))))))))
```
There are 2^10 ways that can be formatted, and no current optimizations kick in to avoid that rathole.
The slowest file to format in the Flutter repo is popup_menu_test.dart and the main culprit is pathological performance from this. I added a new benchmark for the slowest statement in that file.
With the old formatter, it finishes in 0.088ms. With the new …
=> Don't allow function calls to be block arguments.

benchmark/run.dart, lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/cli/summary.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/piece.dart, lib/src/profile.dart
I'm not generally a fan of leaving debug-only code in a codebase, but the recursive nature of the formatter makes it really hard to use the DevTools CPU profiler effectively, and I'm tired of temporarily adding this code and deleting it all the time.
When profiling is disabled, it doesn't seem to effect the performance, so I think it's reasonable to just leave it in.
=> Add some manual profiling instrumentation.

lib/src/back_end/solution.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/list.dart
There's an important optimization where if a piece can tell that it's contents will never fit the given page with without splitting, it can eagerly bind to a specific state. This optimization is really important for forcing large outermost function calls and collections to split so the solver doesn't waste tons of time pointlessly trying to not split them.
Before this change, that optimization only looked at the total page width when determining how much "room" a piece has. That's nice because it means the answer is context free. Thus we can directly pin the piece because no matter the indentation, it's never going to fit.
But it means that when a piece is separately formatted and deeply nested, we don't take that leading indentation into account. Doing so can let us tell that the piece …
=> Take leading indentation into account when constraining by page width.

benchmark/case/interpolation.expect, benchmark/case/interpolation.expect_short, benchmark/case/interpolation.unit, lib/src/front_end/ast_node_visitor.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, test/tall/expression/interpolation.stmt
The old formatter doesn't allow splitting inside interpolation because it almost never looks good. It's better to just let the line overflow, especially if it's a multi-line string. If the user wants it to fit, they're better off splitting the string themselves instead of letting the formatter split inside the interpolation.
Also, a single string can have an unbounded number of arbitrarily large interpolation expressions. Since the expressions can't be separately formatted (because they appear in the middle of a line), this leads to combinatorial performance. It's fairly rare, but it's quite bad when it happens. When I format the Flutter repo, one of the slowest files is packages/flutter/lib/src/material/toggle_buttons.dart. It's spending almost all of its time in:
```
@override
String …
```
=> Don't allow splitting in interpolation expressions.

lib/src/back_end/solution.dart
The last two commits clash and somehow the tests didn't fail on GitHub before merging. Maybe because I didn't merge the second commit with main on the PR branch before merging?
The string interpolation optimization pins pieces inside interpolation expressions. The page width optimization tries to bind pieces if it can tell they will always split. Those two optimizations collide if you have a very long expression inside a string interpolation.
The interpolation optimization pins it to *not* split, but then the later optimization tries to constrain it to always split, which fails.
This fixes that by skipping the page width optimization if the piece is already pinned.
=> Don't apply the page width optimization to already pinned pieces.

.gitignore, benchmark/run.dart, lib/src/debug.dart
I'm working on optimizations and it's increasingly clear that performance problems aren't uniformly distributed. An optimization might dramatically improve some formatting corners of the language while not touching (or possibly slightly regressing) others.
To make it easier to see the effect of a change, this makes it easier to run a bunch of benchmarks, compare all of them to baselines and show the relative changes.
=> Make it easier to run and compare multiple benchmarks.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/short/source_visitor.dart
In order to fix these, I need to move to the new API, but that API requires package macros which doesn't currently support any stable versions of the Dart SDK.
Analyzer will continue to support the old API until analyzer 7.0.0 ships, so it's safe to continue using the old API with the current constraint that dart_style has on analyzer.
So, for now, just ignore the warnings and leave a TODO to fix them after Dart 3.4.0 ships and we can move to the new analyzer.
=> Ignore warnings from deprecated analyzer APIs for now.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart
One important optimization to avoid trying a bunch of dead end solutions is to see if we can eagerly determine that a piece will always end up in some state based on just the size of its contents and the page width. In order to apply that optimization, we walk the piece tree when constructing the solution and ask each piece if it can be eagerly bound.
Unfortunately, that traversal itself has significant overhead:
```
Times (ms)
AstNodeVisitor build Piece tree               =    777.852
AstNodeVisitor.run()                          =   4166.931
CodeWriter.format() write separate piece text =     46.461
PieceWriter.finish() format piece tree        =   3383.440
Solution bind by page width                   =    442.435
Solution.mergeSubtree()                       =    110.427
Solver …
```
=> Bind pieces based on page width during formatting.

test/tall/regression/other/dart.unit
These are things he noticed when trying the old prototype formatter. The real implementation does somewhat better than the prototype, but these may not still have the ideal formatting.
For the first one, there is still a TODO to consider tweaking the heuristics for block arguments, so I'm going to just land this test the way it's currently behaving and then we can revisit it when more of the regression tests are migrated.
cc @jakemac53
=> Add a couple of regression tests for examples from Jake.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/tall/function/default_value.unit, test/tall/function/metadata.unit, test/tall/regression/0200/0247.unit, test/tall/regression/0300/0387.unit
The AST node for a parameter with both metadata and a default value looks like:
DefaultValueFormalParameter
FormalParameter
The inner node has the metadata and the outer one has the default value. Prior to this PR, that meant that we'd create an AssignPiece for the default value whose left-hand side piece was the function parameter and its metadata. That meant that when the metadata split, the outer AssignPiece would be forced to split.
This slightly awkward change makes the piece structure reflect how the user (and, alas, not Analyzer) thinks of the syntax where the metadata is part of the entire parameter and the default value is inside the parameter.
Fix #1461.
=> Correct indentation on parameters with both metadata and default values.

lib/src/front_end/ast_node_visitor.dart, test/tall/regression/0600/0616.unit, test/tall/regression/0700/0782.unit
=> Ensure a blank line between the directives and the declarations.

benchmark/case/large.expect, lib/src/front_end/sequence_builder.dart, test/tall/regression/1400/1415.unit, test/tall/statement/block_comment.stmt, test/tall/top_level/comment.unit
Preserving blank lines between comments and code was mostly working correctly except for one edge case: A blank line between the *first* comment at the top level of a file and the subsequent code would get discarded. This fixes that.
Fix #1415.
=> Preserve a blank line after a leading top-level comment.

lib/src/front_end/delimited_list_builder.dart, test/tall/declaration/enum.unit, test/tall/declaration/enum_comment.unit, test/tall/declaration/enum_metadata.unit, test/tall/expression/list.stmt, test/tall/expression/list_comment.stmt, test/tall/expression/list_preserve_newlines.stmt, test/tall/expression/map.stmt, test/tall/expression/map_comment.stmt, test/tall/expression/map_preserve_newlines.stmt, test/tall/expression/record.stmt, test/tall/expression/record_comment.stmt, test/tall/expression/record_preserve_newlines.stmt, test/tall/expression/set_preserve_newlines.stmt, test/tall/expression/switch.stmt, test/tall/expression/switch_comment.stmt, test/tall/invocation/function.stmt, test/tall/pattern/list.stmt, test/tall/pattern/map.stmt, test/tall/pattern/object.stmt, test/tall/pattern/record.stmt, test/tall/regression/0300/0394.stmt, test/tall/regression/0600/0606.unit, test/tall/regression/1400/1469.stmt
This is consistent with the old formatter and lets users break groups of elements into "sections" inside basically all delimited constructs: lists, maps, objects, argument lists, enums, etc.
Fix #1469.
=> Preserve one blank line between elements in delimited lists.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/assign.dart, test/tall/invocation/chain_postfix.stmt
These are all things we have either done already, have filed issues, or I don't have any plans to do at this point.
=> Remove a bunch of TODO(tall) and TODO(perf) comments that aren't needed.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/assign.dart, lib/src/piece/for.dart, test/tall/statement/for_in.stmt
One of the reasons that AssignPiece is so hairy is because it handles both splitting after the operator ("=", ":", etc.) and before "in".
Splitting out for-in loops to their own Piece class lets us get rid of a little of that complexity.
Also, I thought that was the only reason that the operator is a separate Piece. That's actually not true because we also need the LHS to be its own piece for applyConstraints().
Even so, I still think it's a little easier to understand with for-in loops being their own piece.
I also slightly tweaked the formatting of for-in loops. In the rare case where the left side block splits, we now indent it and split at "in". This is consistent with the old style. I don't have a strong preference, but I think it looks a little neater this way.
=> Don't use AssignPiece for for-in loop "in" clauses.

benchmark/directory.dart, benchmark/run.dart, lib/src/profile.dart, lib/src/testing/benchmark.dart, lib/src/testing/test_file.dart
Many of the optimizations I'm trying have a relatively small improvement. That can make it hard to tell if they are actually an improvement if there is enough variance in the runs that they are lost in the noise.
AOT builds don't need warm-up time and seem to have generally lower variance than JIT runs. Also, they are how the shipped formatter is run in `dart format`. So this adds support to the two benchmark scripts for running themselves in AOT snapshot mode.
I added support for this directly to the scripts instead of just manually compiling and running them on the command line (which works fine) because this way it's less error-prone. I don't have to remember to re-compile the AOT snapshot and risk using an old build which is an easy mistake to make when the only behavioral difference …
=> Support running benchmarks in AOT mode.

test/tall/regression/other/flutter.unit
An important optimization in the formatter is that it will format a subtree of the Piece tree separately and weave the result back into the parent Solution when possible. Part of that process is adding in any bound states, overflow characters, and costs determined in the subtree.
Surprisingly, those rarely actually come into play in terms of affecting the outermost winning solution. I'm not sure exactly why, but if you just merge in the subtree solution's text and discard the bound states, overflow, and cost... all the tests still pass.
But after testing on a large corpus, it turns out that in more complex real-world examples, it *is* important to copy that data back over. So I grabbed an example whose formatting was affected and added this as a sort of regression test.
=> Add test that tickles subtree merging.

benchmark/case/conditional.expect, benchmark/case/conditional.expect_short, benchmark/case/conditional.unit, lib/src/back_end/solver.dart, lib/src/front_end/ast_node_visitor.dart, test/tall/expression/condition.stmt, test/tall/regression/0400/0407.unit, test/tall/regression/0700/0713.stmt, test/tall/regression/0700/0722.stmt, test/tall/regression/0900/0927.unit
When testing the new formatter on a large corpus, I noticed the solver would get stuck on large conditional chains because (unfortunately), we can't separately format the else clause of a split conditional expression. By merging long conditional chains into a single InfixPiece, we can separately format all but the very last dangling else clause.
While I was at it, I also put a hard cap in the number of solutions the solver will try in case it still gets stuck. The old formatter has a similar limit. It's rare for real-world code to hit this limit in the new solver, but it's better than getting totally stuck when it happens.
=> Flatten chained conditionals.

benchmark/directory.dart, lib/src/back_end/solver.dart, lib/src/short/chunk.dart, lib/src/short/chunk_builder.dart, lib/src/short/line_splitting/solve_state.dart, lib/src/short/line_splitting/solve_state_queue.dart, lib/src/short/rule/rule.dart, lib/src/short/source_visitor.dart
This helps comparing the different phases in the two implementations against each other.
Also, I added support to benchmark/directory.dart to run in tall or short style.
=> Add some profiling instrumentation to the old formatter.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/piece/piece.dart
The solver works by incrementally building a up a solution by binding pieces to states one at a time. To avoid wasting time exploring solutions that are pointless, it only looks at unbound pieces in play when the first line containing overflow characters or an invalid newline as written.
Before this PR, it only looked at the *first* unbound piece on that line. Often, the first piece on the line is not the one that actually needs to split. For example, in:
```dart
//                    |
variable = function(argument);
```
Here, the first piece on the overflowing line is the AssignPiece for the `=`, but the piece we actually want to split at is the ListPiece for the argument list.
To handle that, the solver currently tries binding the first piece to all values, including State.unsplit, even …
=> Use all unsolved pieces on the offending line as expand pieces.

lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/front_end/piece_writer.dart, lib/src/front_end/sequence_builder.dart, lib/src/piece/assign.dart, lib/src/piece/case.dart, lib/src/piece/chain.dart, lib/src/piece/clause.dart, lib/src/piece/constructor.dart, lib/src/piece/control_flow.dart, lib/src/piece/for.dart, lib/src/piece/if_case.dart, lib/src/piece/infix.dart, lib/src/piece/list.dart, lib/src/piece/piece.dart, lib/src/piece/sequence.dart, lib/src/piece/text.dart, lib/src/piece/type.dart, lib/src/piece/variable.dart, test/tall/declaration/class_comment.unit, test/tall/declaration/extension_type_comment.unit, test/tall/statement/block_comment.stmt, test/tall/statement/switch_comment.stmt
Propagate newline constrains eagerly when binding states in a Solution.
One of the main ways the formatter defines its formatting style is by having constraints that prohibit newlines in some child pieces when a parent is in a given state.
The two simplest examples (which cover a large amount of code) is that when an InfixPiece or a ListPiece is in State.unsplit, they don't allow any newlines in any of their children. That constraint effectively creates the desired style which is that a split inside an infix operand or list element forces the surrounding expression to split.
Whenever we bind a parent piece to some state, we can now ask it if it allows any of its children to contain newlines. For any given child, if the answer is "no" then:
-   If the child is already bound to a state that …
=> Invalidate eagerly by newline constraint

benchmark/run.dart, lib/src/testing/benchmark.dart, test/utils.dart
This avoids calling group() after an async pause, which breaks running short_format_test.dart and tall_format_test.dart outside of the test runner.
cc @scheglov
=> Make testBenchmarks() synchronous.

test/utils.dart
I can't test this locally, but I think this should fix it.
Fix #1501.
=> Fix tall_format_test.dart on Windows.

lib/src/ast_extensions.dart
This commit fixes a subtle bug in the formatter which is currently covered up by an analyzer bug. The formatter bug is this: `AstNodeExtensions.firstNonCommentToken` assumes that if an AST node doesn't implement `AnnotatedNode`, then it can't possibly begin with a documentation comment, so it is safe to simply defer to `beginToken`. But that isn't true `DefaultFormalParameter` doesn't implement `AnnotatedNode`, but its first child is a `NormalFormalParameter`, which *can* begin with a documentation comment.
Currently, analyzer bug https://github.com/dart-lang/sdk/issues/56313 prevents `NormalFormalParameter.beginToken` from properly accounting for the presence of the documentation comment, so as a result, `AstNodeExtensions.firstNonCommentToken` works correctly on …
=> Fix firstNonCommentToken in anticipation of analyzer fix.

lib/src/cli/format_command.dart, lib/src/cli/formatter_options.dart, lib/src/cli/options.dart, lib/src/io.dart, test/command_test.dart, test/dart_formatter_test.dart
This option is hidden for now because support for traversing the surrounding directories to look for a package config isn't implemented yet. Once that's working too, I'll make the option visible.
This just adds support for explicitly specifying a version through the command line.
=> Allow passing a language version to the formatter CLI.

lib/src/front_end/chain_builder.dart, test/tall/regression/0400/0407.unit, test/tall/regression/0400/0489.stmt, test/tall/regression/0800/0881.unit, test/tall/regression/other/misc.stmt
We always split a cascade if it has multiple sections. We don't require it to split if it has only one:
```dart
cascadeTarget..method(argument);
```
We also don't require it to split if the section is a method call whose argument list splits:
```dart
cascadeTarget..method(
argument,
);
```
But the section might not be an immediate method call like `method()` here. It could be some longer call chain as in:
```dart
cascadeTarget..some.property.chain.method(argument);
```
In that case, if the ultimate trailing argument list splits, I think it's better to force the cascade section to split too:
```dart
cascadeTarget..some.property.chain.method(
argument,
);
// Better:
cascadeTarget
..some.property.chain.method(
argument,
);
```
Otherwise, I think the preceding call chain gets sort of buried …
=> Force a cascade to split if an indirect method call section splits.

lib/src/front_end/piece_factory.dart, lib/src/piece/clause.dart, lib/src/piece/type.dart, test/tall/declaration/class_clause.unit, test/tall/declaration/extension.unit, test/tall/declaration/extension_type.unit, test/tall/regression/other/misc.unit
I think it looks weird if the `extends`, etc. clauses hang immediately after the `>` when the type parameters split.
Since import/export directives use the same piece, this nominally affects them too but in practice it's extremely rare for there to be a newline in an import before any other clauses.
While I was at it, I cleaned up the way we build a piece tree for directives. That's some of the oldest code in the new formatter and was more complex than it needed to be. There was no need to use both an InfixPiece and a ClausesPiece since they do basically the same thing.
=> If a class's type parameters split, force the clauses to split too.

bin/format.dart, lib/src/cli/format_command.dart, lib/src/cli/options.dart, lib/src/dart_formatter.dart, lib/src/io.dart, lib/src/language_version_cache.dart, pubspec.yaml, test/command_test.dart, test/io_test.dart, test/language_version_cache_test.dart, test/utils.dart
When formatting file paths using the formatter CLI, look for a surrounding package (identified by a package config) to infer the default (i.e. not `// @dart=`) language version for each formatted file.
Currently, this behavior only happens when the tall-style experiment is enabled. When that experiment ships, it will be the default behavior. If the user passes an explicit language version using "--language-version", then no directory searching happens.
This only affects the CLI behavior. The library API never searches the file system. Also, when passing input to the formatter CLI over stdin, it doesn't search the file system.
=> Use surrounding packages to infer language version in the CLI.

test/tall/regression/other/misc.unit
These are things I noticed when formatting a corpus using the old prototype version of the new style. Finally got around to adding tests for them. Fortunately, they format as I expect with the new formatter.
Having `_api` hanging on the end of the first line doesn't look *great* in this example, but I think it's mostly because it's unusual that the function has such a long signature followed by a very small target expression. In general, it seems to look good to hang the target of a call chain at the end of the same line as a `=>` member body.
=> Add a couple of regression tests.

lib/src/back_end/code.dart, lib/src/back_end/code_writer.dart, lib/src/back_end/solution.dart, lib/src/back_end/solver.dart, lib/src/front_end/piece_writer.dart
Before this PR, CodeWriter eagerly built a complete string of formatted code using a StringBuffer. This is simple and works OK, but it's a little slow when separate formatting gets involved. Since a subtree of a Piece tree might be formatted separately, it means we often build a string using a StringBuffer only to then append that result to some surrounding StringBuffer, recursively.
This PR introduces a slightly more abstract representation for "formatted code but not quite a single string". It lets us compose separately formatted subtrees by just adding a single existing object to a list.
The performance gain isn't huge, but is measurable:
```
Benchmark (tall)                fastest   median  slowest  average  baseline
-----------------------------  --------  -------  -------  ------- …
```
=> Create a second IR between Pieces and output string.

lib/src/front_end/ast_node_visitor.dart, test/tall/declaration/extension_type.unit, test/tall/declaration/extension_type_comment.unit, test/tall/regression/1500/1505.unit
I guess trailing commas aren't allowed there. Who knew?
Fix #1505.
=> Don't write a trailing comma in extension type representation clauses.

CHANGELOG.md, lib/src/short/source_visitor.dart, test/short/regression/1300/1321.unit, test/tall/regression/1300/1321.unit
If you have a parameter that:
- uses "this." or "super.",
- and also uses the old function-typed formal parameter syntax,
- and also is a generic function...
then the short style formatter would drop the type parameters on the floor. The tall style already does the right thing.
Fix the short style and add regression tests for both.
Fix #1321.
=> Preserve type parameters in function-typed "this." and "super." params.

lib/src/front_end/ast_node_visitor.dart, lib/src/piece/assign.dart, test/tall/function/default_value.unit, test/tall/function/expression_body.unit, test/tall/regression/0100/0108.unit, test/tall/regression/0200/0217.stmt, test/tall/regression/0400/0474.unit, test/tall/regression/0500/0500.unit, test/tall/regression/0500/0557.unit, test/tall/regression/0500/0584.unit, test/tall/regression/0700/0721.unit, test/tall/regression/1100/1190.unit, test/tall/regression/1200/1253.unit, test/tall/regression/1400/1463.unit, test/tall/regression/other/misc.unit
We use the same AssignPiece rule for `=`, `=>`, and `:`. And that rule uniformly handles all kinds of block-formattable right hand sides: collection literals, switch expressions, and function calls. For the most part, that works well and provides nice consistent formatting. Users generally like:
```dart
// Better:
variable = [
long,
list,
literal,
];
// Worse:
variable =
[long, list, literal];
```
And:
```dart
// Better:
SomeWidget(
children: [
long,
list,
literal,
],
);
// Worse:
SomeWidget(
children:
[long, list, literal],
);
```
And (with somewhat less consensus):
```dart
// Better:
variable = function(
long,
argument,
list,
);
// Worse:
variable =
function(long, argument, list);
```
Also, users have long requested and seem to like:
```dart
// Better:
class C {
List<String> makeStuff() …
```
=> When the RHS of `=>` is a function call, prefer to split at the `=>`.

lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/delimited_list_builder.dart, test/tall/expression/switch.stmt, test/tall/invocation/block_argument_multiple.stmt, test/tall/regression/1500/1529.stmt
I figured that since other comma-delimited expression forms don't split
if they don't have to, switch expressions should be the same. But I
went and checked on a huge corpus and every single place where a switch
expression wasn't split was clearly much worse than splitting it would
be.
Fix #1529.
=> Always split switch expressions

lib/src/ast_extensions.dart, test/tall/regression/0400/0466.unit, test/tall/regression/1400/1463.unit, test/tall/regression/1500/1526.stmt, test/tall/regression/1500/1531.stmt, test/tall/variable/local.stmt
In assignment-like context, if the RHS is an await expression and the inner expression can be block formatted, then let the whole await expression be block formatted.
This comes into play in assignments, but not in argument lists which are the other place where block formatting is a thing. That's because in argument lists, we *don't* treat function calls as block formattable. (This is both for performance and style reasons). There's no point in awaiting any of the other kinds of block-formattable expressions: collection literals or function expressions.
So this really just benefits assignments, named argument expressions, and `=>` bodies. But it definitely makes those look better.
Fix #1531.
=> Block-format await expressions if the inner expression allows it.

test/tall/regression/other/large.stmt
This is a sanitized statement from internal code that was causing the old formatter to choke.
=> Add a regression test for a large statement.

lib/src/front_end/piece_factory.dart
The Dart analyzer will soon be changed so that if the `default` clause of a `switch` statement is determined to be unreachable by the exhaustiveness checker, a new warning of type
`unreachable_switch_default` will be issued. This parallels the behavior of the existing `unreachable_switch_case` warning, which is issued whenever a `case` clause of a `switch` statement is determined to be unreachable. For details see https://github.com/dart-lang/sdk/issues/54575.
This PR deletes an unreachable `default` clause from `dart_style` now, to avoid a spurious warning when the analyzer change lands.
---
<details>
- Larger or …
=> Delete unreachable `default` clause.

lib/src/ast_extensions.dart, lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, lib/src/piece/list.dart, test/tall/invocation/block_argument_description.stmt, test/tall/invocation/block_argument_multiple.stmt, test/tall/invocation/block_argument_named.stmt, test/tall/invocation/block_argument_other.stmt, test/tall/invocation/block_argument_string.stmt, test/tall/regression/0100/0146.unit, test/tall/regression/0200/0243.stmt, test/tall/regression/0300/0394.stmt, test/tall/regression/0400/0421.unit, test/tall/regression/0400/0478.stmt, test/tall/regression/0500/0568.unit, test/tall/regression/0800/0809.unit, test/tall/regression/1400/1441.unit, test/tall/regression/1500/1526.stmt, test/tall/regression/1500/1527.unit, test/tall/regression/1500/1528.stmt, test/tall/regression/1500/1531.stmt, test/tall/regression/1500/1543.unit
This produces output that better matches what users expected in the associated issues. I think it also looks better in the affected regression tests. And I ran this on a large corpus and looking at the diffs, these rules seem to be much better across the board.
The new rules are basically:
* A block formatted argument list can't end up with named arguments on multiple lines.
* Only one trailing argument is allowed after the block argument.
The existing rules are also kept:
* Prefer a function block argument over a collection one.
* Only allow a single block argument.
* Allow the first argument to be adjacent strings with a later function block argument (to handle calls like `test()` and `group()`).
Fix #1527.
Fix #1528.
Fix #1543.
=> Tweak block argument heuristics

CHANGELOG.md, lib/src/front_end/piece_factory.dart, lib/src/short/source_visitor.dart, test/short/regression/1500/1544.unit, test/short/whitespace/directives.unit, test/tall/regression/1500/1544.unit, test/tall/top_level/import.unit
It would output the `as` clause after the `if` clauses, which isn't syntactically valid. Apparently no one has ever had a conditional import with as prefix because this was a bug in both the old and new formatters and has been a bug in the old formatter forever.
Fix #1544.
=> Correctly format imports with both `as` and `if` clauses.

lib/src/front_end/piece_factory.dart, lib/src/short/source_visitor.dart, test/short/whitespace/directives.unit, test/tall/top_level/import.unit
PR #1550 fixed the bug where if you had both clauses, it would output them in the *wrong* order. But it turns out that the parser today allows them in *either* order even though the language spec doesn't.
Since I've seen a handful of cases like this in the wild, instead of just failing to format, simply preserve the clause order that the user wrote.
=> Handle imports with "as" and "if" clauses in either order.

lib/src/front_end/chain_builder.dart, test/tall/invocation/cascade_mixed.stmt
I found this weird corner case in the wild when formatting a large corpus.
=> Don't crash on an index cascade section followed by a method chain.

test/command_test.dart
I guess Dart on Windows uses `/` as a path separator in stack traces?
I'm not sure if it's safe to rely on that, so just tweaking the expectation to not care about the separator at all.
=> Fix test that fails on Windows.

benchmark/case/flutter_scrollbar_test.expect, lib/src/front_end/delimited_list_builder.dart, test/tall/invocation/block_argument_named.stmt, test/tall/invocation/block_argument_other.stmt, test/tall/regression/0100/0198.stmt, test/tall/regression/0300/0394.stmt, test/tall/regression/0300/0398.stmt, test/tall/regression/0700/0798.stmt, test/tall/regression/0800/0809.unit, test/tall/regression/1100/1197.unit
There are three ways an argument list can be formatted:
```dart
// 1. All inline:
function(argument, another);
// 2. Block formatted:
function(argument, [
element,
element,
]);
// 3. Tall style:
function(
argument,
another,
);
```
One of the trickiest parts of the formatter is deciding the heuristics to choose between 2 and 3.
Prior to this PR, there is a fairly subtle rule: Arguments before the block argument can be named or not, the block argument can be named or not, and the argument after the block argument can be named or not, but only one of those three sections can have a named argument.
The intent of that rule is to allow named block arguments and named non-block arguments, while avoiding multiple argument names on the same line when block formatted. Also, it allows an argument …
=> Don't allow a block argument to be named.

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml
Main is two commits ahead of what rolled into google3, but those two changes should be safe, so I'm ready to publish this.
Getting this out will enable other packages that use dart_style as a library to update their constraint on it to require 2.3.7 so that they can start passing in a language version to the `DartFormatter()` constructor.
=> Bump version to publish 2.3.7.

CHANGELOG.md, benchmark/directory.dart, benchmark/run.dart, example/format.dart, lib/src/cli/options.dart, lib/src/dart_formatter.dart, lib/src/io.dart, lib/src/testing/test_file.dart, pubspec.yaml, test/dart_formatter_test.dart, test/short/whitespace/switch.stmt, test/tall/statement/switch_legacy.stmt, test/utils.dart, tool/update_tests.dart
This is a breaking change, so bumping the major version of dart_style, the first time I've done that since the null safety migration (!).
=> Make the language version parameter to DartFormatter mandatory.

CHANGELOG.md, lib/src/cli/format_command.dart, lib/src/io.dart, lib/src/language_version_cache.dart, test/cli_test.dart, test/language_version_cache_test.dart
Use --stdin-name as a file path for inferring the language version.
If --stdin-name is given, then look for a surrounding package config to
infer the default language version from for code read from stdin. To
avoid that behavior, you can pass in a language version explicitly
using --language-version.
Fix #1530.
=> Stdin name search

benchmark/case/interpolation_1516.expect, benchmark/case/interpolation_1516.expect_short, benchmark/case/interpolation_1516.unit, test/tall/regression/1500/1516.unit
The underlying issue was already fixed by #1448. This just tracks that we don't regress performance or output.
Fix #1516.
=> Add benchmark and regression test for #1516.

lib/src/front_end/piece_factory.dart, test/tall/statement/try.stmt, test/tall/statement/try_comment.stmt
Apparently the language doesn't allow them. Who knew?
Fix #1570.
=> Don't write trailing commas in split catch clauses.

lib/src/dart_formatter.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/comment_writer.dart, lib/src/front_end/piece_writer.dart, test/tall/other/format_off.unit, test/tall/other/format_width.unit
If the code being formatted contains a comment anywhere in it like:
```
// dart format width=123
```
Then the code is formatted at that width instead of the default width.
The intent is that tools that generate code and then format it will put this comment in the generated code. That way, the tool doesn't have to handle the complex logic to find a surrounding analysis_options.yaml file and get the user's project-wide page width configuration.
End users may also want to use this comment in rare cases. For example, maybe they have a library that contains a large value of data that looks better as a big wide table but they don't want their entire project to have a wider page width.
=> Allow a comment in code to explicitly configure the page width.

lib/src/front_end/ast_node_visitor.dart, lib/src/piece/bound.dart, lib/src/piece/type_parameter_bound.dart, test/tall/declaration/class_type_parameter.unit, test/tall/regression/1500/1568.unit
The tall style was already doing a better job on #1568 than the old short style does. (I don't know why it leaves an overly long line there. It seems like a bug but perhaps a nasty subtle one in the solver.)
But it still didn't allow splitting before `extends` in a bound which could leave long lines in cases where the type parameter and bound name are both quite long. Rare, but we may as well do a better job.
So this introduces a new piece that allows splitting before `extends` if needed.
Fix #1568.
cc @stereotype441 Take a look at the regression test if you want to see how the new style handles your example.
=> Better formatting for long type parameter bounds.

CHANGELOG.md, lib/src/cli/format_command.dart, test/cli/page_width_test.dart
The formatter has always been inconsistent about how to refer to the limit that it tries to fit code in. The option name (which is older than when I started working on the formatter) is "--line-length". But the public API and all of the internal code uses "page width".
This renames that option to "--page-width". The old name is still supported (but hidden in help) for backwards compatibility.
In practice, this option isn't used often, so this likely won't affect many users. We've already made a major version bump, so now seems like a good time to clean things up as much as possible.
cc @johnmccutchan since the inconsistency was bugging you. :)
=> Rename "--line-length" option to "--page-width".

CHANGELOG.md, benchmark/directory.dart, benchmark/run.dart, example/format.dart, lib/src/cli/format_command.dart, lib/src/config_cache.dart, lib/src/constants.dart, lib/src/dart_formatter.dart, lib/src/io.dart, lib/src/testing/test_file.dart, test/README.md, test/cli/language_version_test.dart, test/cli/page_width_test.dart, test/dart_formatter_test.dart, test/utils.dart, tool/update_tests.dart
This PR does a few things:
- Remove the "tall-style" experiment flag and treat it as always enabled.
- Use language version instead of the experiment flag to determine which style you get. If the version is 3.7 or higher, you get the tall style. Otherwise, you get the short style.
- Clean up the CHANGELOG.md and README.md a bit. I'll probably do some more copy editing on them before this gets published, but I wanted to get things roughly in order.
cc @leafpetersen @mit-mit
=> Ship the "tall-style" experiment.

lib/src/front_end/piece_factory.dart, test/tall/function/comment.unit, test/tall/function/metadata.unit, test/tall/regression/other/dart.unit
This situation rarely occurs in practice, since users typically put the comment before the metadata too (which is why we never noticed this bug until now).
But if it does occur, it's definitely wrong to force the return type to split unnecessarily.
=> Don't split return type if there is a comment after function metadata.

lib/src/front_end/delimited_list_builder.dart, lib/src/front_end/piece_factory.dart, pubspec.yaml, test/tall/expression/list_comment.stmt, test/tall/regression/1500/1584.unit
A line comment in a collection literal triggers special formatting where we allow multiple elements in a single line, like:
```
list = [
// Comment.
1, 2, 3,
4, 5,
6,
];
```
The formatter models that by having a DelimitedListBuilder for the entire collection literal. Then the elements that should be packed onto a single line are formatted using a separate DelimitedListBuilder for each line.
In the very rare case where you have a comment after the last element on a line but *before* the subsequent comma, the comment would get dropped. This is because the comment was sitting in the inner DelimitedListBuilder for the line waiting to be put somewhere, but we then discard that builder to start a new line or when the whole list is done.
This fixes that. Whenever we're done with a line, we hoist …
=> Don't drop comments in collection literals with preserved newlines.

lib/src/ast_extensions.dart, test/tall/regression/1500/1586.unit
This is a funny corner of the analyzer AST API where a PatternVariableDeclarationStatement wraps an inner PatternVariableDeclaration. The statement class isn't itself an AnnotatedNode so doesn't get caught by the first couple of cases. But its beginToken comes from the inner PatternVariableDeclaration, which *is* an AnnotatedNode, so we need to recurse into that.
Fix #1586.
=> Don't crash on a doc comment before a pattern variable statement.

README.md, lib/src/dart_formatter.dart, lib/src/front_end/piece_factory.dart, lib/src/front_end/piece_writer.dart, lib/src/piece/chain.dart, lib/src/piece/control_flow.dart, lib/src/piece/piece.dart, lib/src/piece/variable.dart, lib/src/string_compare.dart
Updated the example in the README to one that uses the new style. I also took the opportunity to find a more interesting example and generally rewrote things based on how the formatter is used today.
When we were in the middle of the rewrite, I used "TODO(tall)" and "TODO(perf)" comments to track things I wanted to look into before I considered the rewrite "done". Now that the rewrite is basically good enough, I went through those. If I think the TODO is no longer worth doing at all, I just deleted it. Otherwise, I turned it into a general "TODO(rnystrom)" for us to keep in mind at some unspecified time.
=> Clean up README and TODO comments.

lib/src/piece/chain.dart
We were still passing in `allowNewlines` to `_formatCall()` even though that parameter was no longer used once Piece got the `allowChildInState()` API. So I removed that.
Then I noticed that the switch in `_formatCall()` could be more cleanly handled by having the cases in `format()` calculate `separate` directly. So I did that.
That left `_formatCall()` not actually doing anything useful, so I got rid of it.
There are no behavioral change, it's just a code clean-up.
=> Simplify ChainPiece.

lib/src/analysis_options/analysis_options_file.dart, test/analysis_options/analysis_options_file_test.dart, test/utils.dart
Fixes https://github.com/dart-lang/dart_style/issues/1591
The implementation is fairly simple. If the `include` value in an analysis options file is a List, then iteratively merge included options files.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md# …
=> Support a list of include paths in analysis options

lib/src/dart_formatter.dart, test/cli/language_version_test.dart, test/dart_formatter_test.dart
The formatter uses an incoming language version to control how the formatted code is parsed. The langauge version is also used to determine whether you get the short or tall style.
Prior to this PR, a `// @dart=` version comment in the formatted code would affect the language version the code is parsed at. But it wouldn't use that comment to determine whether you get the short or tall style. This fixes that.
Fix #1599.
cc @davidmorgan
=> Make "// @dart=" version comments affect the applied style.

CHANGELOG.md, pubspec.yaml
How was this tested? First I set the constraint to `^7.0.0` and ran `dart pub upgrade` with Dart 3.5.0. Dart 3.5.0 did not like that, because of macros, and failed to version-solve. I then ran `dart pub upgrade` with a Dart 3.7.0 dev release, and obtained a successful version-solve, using analyzer 7.0.0. The code analyzes cleanly, and all 5108 tests pass.
---
<details>
- Most changes should add …
=> Allow analyzer ^7.0.0 dep

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml, tool/grind.dart
Also fixed the format-self call in the grinder script which was still using the old CLI format.
=> Bump to publish 3.0.0.

CHANGELOG.md, lib/src/back_end/code_writer.dart, lib/src/dart_formatter.dart, lib/src/piece/leading_comment.dart, lib/src/testing/test_file.dart, pubspec.yaml, test/tall/pattern/cast_comment.stmt, test/tall/regression/1606/1606.unit, test/tall/statement/if_comment.stmt, test/tall/top_level/import_comment.unit, test/utils.dart
In some cases, a line comment can appear between two tokens that otherwise never split, like after "if (" and before the condition. That leads to some tricky edge case behavior. If you formatted:
```dart
if (
// Comment
condition) {
;
}
```
It would see the newline before the comment and decide the comment was a "leading comment" which means it gets attached to the condition expression. Then the formatter would output it like:
```dart
if (// Comment
condition) {
;
}
```
That's because leading comments don't write a newline before themselves. Then if you format that again, there's no newline before the `//`, so now it's a hanging comment. Hanging comments get a space before them, so you get:
```dart
if ( // Comment
condition) {
;
}
```
Really, leading comments (as the name implies) are …
=> Ensure comment formatting is idempotent.

CHANGELOG.md, lib/src/ast_extensions.dart, test/tall/regression/1600/1621.unit
=> Don't crash on doc comments inside local variable declarations.

example/format.dart, lib/src/back_end/code.dart, lib/src/back_end/solver.dart, lib/src/debug.dart
The formatter supports a bunch of debug flags you can enable to see what the solver is doing as it works its magic. That output can be pretty verbose and chatty.
When I added the Code intermediate representation, it got worse. Even more verbose, but less helpful because the Code tree doesn't really show you as much as just seeing the formatted output.
This improves the debug output a few ways:
- Instead of showing the Code tree (which is almost never useful), show the formatted result of that. This is a little tricky because the normal way we lower a Code tree to an output string requires access to the original SourceCode being formatted (in order to support `// dart format off`). The Solver doesn't have that. So instead, there's a new little debug-only visitor to lower Code to a string …
=> Better debug diagnostics in the solver.

lib/src/cli/formatter_options.dart, tool/grind.dart
The workflow for shipping dart_style used to be that we published a new version on pub and then rolled it into the Dart SDK. That meant that the dart_style version number in the SDK accurately described what was in dart_style.
A few years ago, we changed to rolling into the SDK first. That lets us validate dart_style inside google3 before irrevocably publishing, which is a good thing. But it has an unfortunate side effect. If you run `dart format --version`, it shows the *previous* version number of dart_style because the version number only gets bumped when we publish. This is really confusing if you're trying to debug the formatter in the SDK and it appears to be an older version than it actually is.
To fix that, I'm tweaking the workflow slightly. When we begin working on a new version …
=> Update grinder script.

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, test/tall/declaration/typedef.unit, test/tall/regression/1600/1651.unit
=> Allow block formatting record types in typedefs.

CHANGELOG.md, lib/src/piece/chain.dart, test/tall/invocation/chain_property.stmt
I was trying out the new formatter on a corpus after #1687 and saw a bunch of diffs like:
```dart
// Before:
Widget(
name:
some.property.chain,
)
// After:
Widget(
name: some
.property
.chain,
)
```
While the new headline style looks nice for most method call chains, it looks weird if it's only just a series of properties. In particular, a single `foo.bar` looks really silly when split.
This PR bumps the split cost of a chain up if it only contains properties. That leads the solver to prefer splitting the surrounding construct when possible.
=> Avoid splitting chains containing only properties.

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/chain_builder.dart, lib/src/front_end/expression_contents.dart, lib/src/front_end/piece_factory.dart, test/tall/invocation/nested.stmt, test/tall/regression/0300/0394.stmt, test/tall/regression/1500/1527.unit
This is similar to the existing rule where nested non-empty collection literals force the outer one to split. The rules are basically:
* If an argument list contains any named arguments and contains any other calls whose argument lists contain any named arguments (directly or indirectly), then split the outer one. We make an exception where a named argument whose expression is a simple number, Boolean, or null literal doesn't count as a named argument.
* If a list, set, or map literal is the immediate expression in a named argument and one of the above kinds of argument lists (directly or indirectly), then force the collection to split.
```dart
// Before:
Stack(children: [result, Semantics(label: indexLabel)]);
// After:
Stack(
children: [
result,
Semantics(label: indexLabel),
],
);
``` …
=> Eagerly split argument lists based on their contents.

lib/src/front_end/piece_writer.dart, test/tall/regression/1600/1667.unit
In certain locations, if you had multiple inline block comments on the same line, they would get reordered. That in turn would (correctly) trip the formatter's internal "whitespace-only changes" sanity check and lead to it aborting.
Fix #1667.
=> Fix bug with comments being reordered.

.github/ISSUE_TEMPLATE/formatting-issue.md, .github/ISSUE_TEMPLATE/other-request.md
I've been getting a lot of issues lately with screenshots instead of text which isn't super helpful. Adding a couple of issue templates to help guide users towards more actionable issues.
=> Add issue templates.

CHANGELOG.md, lib/src/front_end/expression_contents.dart, lib/src/front_end/piece_factory.dart, test/tall/invocation/nested.stmt, test/tall/regression/0300/0394.stmt, test/tall/regression/1500/1527.unit, test/tall/regression/other/flutter.unit
Some folks on the Flutter team pointed out that the previous rule is too aggressive and splits even simple common code like:
```dart
Text('Item 1', style: TextStyle(color: Colors.white));
```
That's probably simple enough to stay on one line. So this tweaks the heuristic to allow that to remain unsplit. Where the old heuristic split any argument list with a named argument that contained a nested named argument, this requires there to be at least *three* named arguments.
It's sort of an arbitrary cutoff, but it seems to do a good job when run on a large corpus.
=> Make the eager argument list splitting heuristic more conservative.

lib/src/back_end/solution.dart, test/tall/expression/interpolation.stmt
If a string interpolation contains a splittable expression which in turn contains an expression with a mandatory newline (like a multiline string or `;`), then the solver gets confused.
The splittable expression is already pinned to state 0 to prevent there from being newlines in the string interpolation. But now the newline inside the subexpression tries to force the splittable expression to split.
That leads the solver to invalidate the solution and then try to find something better. Ultimately, it ends up unnecessarily splitting some piece surrounding the interpolated string. (In the examples I've seen in the wild, it's always a function's argument list.)
To avoid that, if a piece is already pinned, then we ignore invalidation from it. This fixes the few rare cases I've seen in a large …
=> Don't invalidate solutions from pinned pieces.

CHANGELOG.md, lib/src/cli/formatter_options.dart, pubspec.yaml
These changes have already rolled into the SDK, Flutter, and google3.
=> Bump version to publish 3.1.0.

CHANGELOG.md, lib/src/dart_formatter.dart, lib/src/exceptions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/short/source_visitor.dart, pubspec.yaml, test/tall/invocation/dot_shorthand.stmt, test/tall/invocation/dot_shorthand_comment.stmt
This is using a workaround for https://github.com/dart-lang/sdk/issues/60840. That issue is fixed and a new version of analyzer is published, but unfortunately there is no corresponding version of test that works with it so I can't upgrade yet.
The workaround is pretty harmless, so I'm fine with it. (The formatter uses similar logic to handle commas which also aren't represented in the AST nodes.)
I pulled the tests here by looking at the language tests for the feature (which are excellent and comprehensive) so I think I covered everything. I verified that the formatter can format everything in the SDK language tests (at least everything that can be parsed because there are error tests in there). Let me know if you see any corners of the syntax I missed. (I didn't realize that you could …
=> Enable language version 3.10 and format dot shorthands.

CHANGELOG.md, lib/src/cli/formatter_options.dart, lib/src/dart_formatter.dart, lib/src/exceptions.dart, lib/src/front_end/ast_node_visitor.dart, lib/src/short/source_visitor.dart, pubspec.yaml, test/tall/expression/collection_null_aware.stmt, test/tall/expression/collection_null_aware_comment.stmt, test/tall/invocation/dot_shorthand.stmt, test/tall/invocation/dot_shorthand_comment.stmt
=> Preserve space between "?" and "." in null aware element dot shorthand.

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/tall/declaration/enum.unit, test/tall/preserve_trailing_commas/enum.unit
Also add the style change to the CHANGELOG.
This build's on @jellynoone's PR #1703 which I merged into a branch instead of main so that I can tweak it a bit. This PR is the tweak. Once this is merged onto the branch, I'll merge the whole branch onto main.
=> Language version preserving the trailing comma in enums with members.

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, lib/src/front_end/piece_factory.dart, test/tall/declaration/enum.unit, test/tall/preserve_trailing_commas/enum.unit
This is the same change you just reviewed + @jellynoone's original PR. Now I'm merging it into main.
=> Preserve trailing commas enum with members

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, test/tall/preserve_trailing_commas/record_type.unit, test/tall/regression/1700/1721.unit
I missed this part of the language when I added support of preserving trailing commas. They should have always been preserved here, so I didn't language version this change. If someone has preserve trailing commas on but isn't on 3.10 yet, I think they will still want this change.
Fix #1721.
=> Make preserved trailing commas apply to record types too.

CHANGELOG.md, lib/src/front_end/ast_node_visitor.dart, pubspec.yaml, test/tall/expression/collection_null_aware.stmt
We fixed the parser so that it can correctly handle:
```dart
[?.property]
```
Even if there is no space between `?` and `.`, it knows to treat it as a dot shorthand inside a null-aware element here. So the formatter doesn't need to force insert a space in there to avoid `?.` from being tokenized as a null-aware access.
See: https://github.com/dart-lang/language/issues/4477
=> Remove special case handling of dot shorthands in null aware elements.

CHANGELOG.md, lib/src/front_end/piece_factory.dart, lib/src/short/source_visitor.dart, pubspec.yaml, test/short/regression/1500/1544.unit, test/short/whitespace/directives.unit, test/tall/regression/1500/1544.unit, test/tall/top_level/import.unit
The language specifies that import configuration URIs must appear before any import prefix, like:
```dart
import 'foo.dart' if (cond) 'bar.dart' as prefix;
```
If a user wrote them in the wrong order:
```dart
import 'foo.dart' as prefix if (cond) 'bar.dart';
```
Then the parser used to not report an error and would accept the code, which would then be compiled successfully. Some users in the wild, probably inadvertently, ended up relying on this. So I added support in the formatter to handle it.
I also filed:
https://github.com/dart-lang/sdk/issues/56641
That issue will be fixed soon:
https://github.com/dart-lang/sdk/issues/61264
It's going to be a parse error to have the clauses in the wrong order. These formatter tests are failing in the bleeding edge SDK. So now it's time to remove the …
=> Remove tests of invalid import syntax.
